var votes=[
    {
        "Party":"REP",
        "Precinct":"101",
        "Votes":"1048"
    },
    {
        "Party":"DEM",
        "Precinct":"101",
        "Votes":"1152"
    },
    {
        "Party":"REP",
        "Precinct":"103",
        "Votes":"1247"
    },
    {
        "Party":"DEM",
        "Precinct":"103",
        "Votes":"1346"
    },
    {
        "Party":"REP",
        "Precinct":"105",
        "Votes":"926"
    },
    {
        "Party":"DEM",
        "Precinct":"105",
        "Votes":"1601"
    },
    {
        "Party":"REP",
        "Precinct":"107",
        "Votes":"1400"
    },
    {
        "Party":"DEM",
        "Precinct":"107",
        "Votes":"1686"
    },
    {
        "Party":"REP",
        "Precinct":"108",
        "Votes":"922"
    },
    {
        "Party":"DEM",
        "Precinct":"108",
        "Votes":"775"
    },
    {
        "Party":"REP",
        "Precinct":"109",
        "Votes":"949"
    },
    {
        "Party":"DEM",
        "Precinct":"109",
        "Votes":"700"
    },
    {
        "Party":"REP",
        "Precinct":"111",
        "Votes":"906"
    },
    {
        "Party":"DEM",
        "Precinct":"111",
        "Votes":"651"
    },
    {
        "Party":"REP",
        "Precinct":"112",
        "Votes":"1060"
    },
    {
        "Party":"DEM",
        "Precinct":"112",
        "Votes":"653"
    },
    {
        "Party":"REP",
        "Precinct":"113",
        "Votes":"930"
    },
    {
        "Party":"DEM",
        "Precinct":"113",
        "Votes":"1053"
    },
    {
        "Party":"REP",
        "Precinct":"115",
        "Votes":"626"
    },
    {
        "Party":"DEM",
        "Precinct":"115",
        "Votes":"751"
    },
    {
        "Party":"REP",
        "Precinct":"116",
        "Votes":"562"
    },
    {
        "Party":"DEM",
        "Precinct":"116",
        "Votes":"544"
    },
    {
        "Party":"REP",
        "Precinct":"117",
        "Votes":"1631"
    },
    {
        "Party":"DEM",
        "Precinct":"117",
        "Votes":"803"
    },
    {
        "Party":"REP",
        "Precinct":"119",
        "Votes":"1458"
    },
    {
        "Party":"DEM",
        "Precinct":"119",
        "Votes":"942"
    },
    {
        "Party":"REP",
        "Precinct":"121",
        "Votes":"1244"
    },
    {
        "Party":"DEM",
        "Precinct":"121",
        "Votes":"1042"
    },
    {
        "Party":"REP",
        "Precinct":"123",
        "Votes":"1312"
    },
    {
        "Party":"DEM",
        "Precinct":"123",
        "Votes":"1147"
    },
    {
        "Party":"REP",
        "Precinct":"125",
        "Votes":"686"
    },
    {
        "Party":"DEM",
        "Precinct":"125",
        "Votes":"396"
    },
    {
        "Party":"REP",
        "Precinct":"127",
        "Votes":"1345"
    },
    {
        "Party":"DEM",
        "Precinct":"127",
        "Votes":"1171"
    },
    {
        "Party":"REP",
        "Precinct":"129",
        "Votes":"1048"
    },
    {
        "Party":"DEM",
        "Precinct":"129",
        "Votes":"1007"
    },
    {
        "Party":"REP",
        "Precinct":"131",
        "Votes":"1449"
    },
    {
        "Party":"DEM",
        "Precinct":"131",
        "Votes":"928"
    },
    {
        "Party":"REP",
        "Precinct":"133",
        "Votes":"1018"
    },
    {
        "Party":"DEM",
        "Precinct":"133",
        "Votes":"360"
    },
    {
        "Party":"REP",
        "Precinct":"135",
        "Votes":"1606"
    },
    {
        "Party":"DEM",
        "Precinct":"135",
        "Votes":"996"
    },
    {
        "Party":"REP",
        "Precinct":"137",
        "Votes":"1263"
    },
    {
        "Party":"DEM",
        "Precinct":"137",
        "Votes":"760"
    },
    {
        "Party":"REP",
        "Precinct":"139",
        "Votes":"1596"
    },
    {
        "Party":"DEM",
        "Precinct":"139",
        "Votes":"702"
    },
    {
        "Party":"REP",
        "Precinct":"141",
        "Votes":"470"
    },
    {
        "Party":"DEM",
        "Precinct":"141",
        "Votes":"524"
    },
    {
        "Party":"REP",
        "Precinct":"145",
        "Votes":"403"
    },
    {
        "Party":"DEM",
        "Precinct":"145",
        "Votes":"398"
    },
    {
        "Party":"REP",
        "Precinct":"149",
        "Votes":"104"
    },
    {
        "Party":"DEM",
        "Precinct":"149",
        "Votes":"89"
    },
    {
        "Party":"REP",
        "Precinct":"151",
        "Votes":"350"
    },
    {
        "Party":"DEM",
        "Precinct":"151",
        "Votes":"359"
    },
    {
        "Party":"REP",
        "Precinct":"153",
        "Votes":"229"
    },
    {
        "Party":"DEM",
        "Precinct":"153",
        "Votes":"250"
    },
    {
        "Party":"REP",
        "Precinct":"157",
        "Votes":"210"
    },
    {
        "Party":"DEM",
        "Precinct":"157",
        "Votes":"163"
    },
    {
        "Party":"REP",
        "Precinct":"159",
        "Votes":"1412"
    },
    {
        "Party":"DEM",
        "Precinct":"159",
        "Votes":"888"
    },
    {
        "Party":"REP",
        "Precinct":"160",
        "Votes":"839"
    },
    {
        "Party":"DEM",
        "Precinct":"160",
        "Votes":"884"
    },
    {
        "Party":"REP",
        "Precinct":"163",
        "Votes":"97"
    },
    {
        "Party":"DEM",
        "Precinct":"163",
        "Votes":"261"
    },
    {
        "Party":"REP",
        "Precinct":"165",
        "Votes":"434"
    },
    {
        "Party":"DEM",
        "Precinct":"165",
        "Votes":"728"
    },
    {
        "Party":"REP",
        "Precinct":"169",
        "Votes":"198"
    },
    {
        "Party":"DEM",
        "Precinct":"169",
        "Votes":"1287"
    },
    {
        "Party":"REP",
        "Precinct":"175",
        "Votes":"580"
    },
    {
        "Party":"DEM",
        "Precinct":"175",
        "Votes":"1141"
    },
    {
        "Party":"REP",
        "Precinct":"179",
        "Votes":"480"
    },
    {
        "Party":"DEM",
        "Precinct":"179",
        "Votes":"639"
    },
    {
        "Party":"REP",
        "Precinct":"203",
        "Votes":"250"
    },
    {
        "Party":"DEM",
        "Precinct":"203",
        "Votes":"1188"
    },
    {
        "Party":"REP",
        "Precinct":"205",
        "Votes":"675"
    },
    {
        "Party":"DEM",
        "Precinct":"205",
        "Votes":"1658"
    },
    {
        "Party":"REP",
        "Precinct":"207",
        "Votes":"78"
    },
    {
        "Party":"DEM",
        "Precinct":"207",
        "Votes":"1594"
    },
    {
        "Party":"REP",
        "Precinct":"209",
        "Votes":"168"
    },
    {
        "Party":"DEM",
        "Precinct":"209",
        "Votes":"990"
    },
    {
        "Party":"REP",
        "Precinct":"213",
        "Votes":"118"
    },
    {
        "Party":"DEM",
        "Precinct":"213",
        "Votes":"1197"
    },
    {
        "Party":"REP",
        "Precinct":"217",
        "Votes":"641"
    },
    {
        "Party":"DEM",
        "Precinct":"217",
        "Votes":"1229"
    },
    {
        "Party":"REP",
        "Precinct":"218",
        "Votes":"180"
    },
    {
        "Party":"DEM",
        "Precinct":"218",
        "Votes":"369"
    },
    {
        "Party":"REP",
        "Precinct":"219",
        "Votes":"703"
    },
    {
        "Party":"DEM",
        "Precinct":"219",
        "Votes":"1219"
    },
    {
        "Party":"REP",
        "Precinct":"221",
        "Votes":"116"
    },
    {
        "Party":"DEM",
        "Precinct":"221",
        "Votes":"265"
    },
    {
        "Party":"REP",
        "Precinct":"223",
        "Votes":"436"
    },
    {
        "Party":"DEM",
        "Precinct":"223",
        "Votes":"1217"
    },
    {
        "Party":"REP",
        "Precinct":"225",
        "Votes":"407"
    },
    {
        "Party":"DEM",
        "Precinct":"225",
        "Votes":"340"
    },
    {
        "Party":"REP",
        "Precinct":"226",
        "Votes":"6"
    },
    {
        "Party":"DEM",
        "Precinct":"226",
        "Votes":"6"
    },
    {
        "Party":"REP",
        "Precinct":"227",
        "Votes":"749"
    },
    {
        "Party":"DEM",
        "Precinct":"227",
        "Votes":"1225"
    },
    {
        "Party":"REP",
        "Precinct":"231",
        "Votes":"565"
    },
    {
        "Party":"DEM",
        "Precinct":"231",
        "Votes":"1452"
    },
    {
        "Party":"REP",
        "Precinct":"233",
        "Votes":"304"
    },
    {
        "Party":"DEM",
        "Precinct":"233",
        "Votes":"661"
    },
    {
        "Party":"REP",
        "Precinct":"237",
        "Votes":"544"
    },
    {
        "Party":"DEM",
        "Precinct":"237",
        "Votes":"1007"
    },
    {
        "Party":"REP",
        "Precinct":"239",
        "Votes":"502"
    },
    {
        "Party":"DEM",
        "Precinct":"239",
        "Votes":"970"
    },
    {
        "Party":"REP",
        "Precinct":"240",
        "Votes":"759"
    },
    {
        "Party":"DEM",
        "Precinct":"240",
        "Votes":"1217"
    },
    {
        "Party":"REP",
        "Precinct":"241",
        "Votes":"28"
    },
    {
        "Party":"DEM",
        "Precinct":"241",
        "Votes":"250"
    },
    {
        "Party":"REP",
        "Precinct":"243",
        "Votes":"437"
    },
    {
        "Party":"DEM",
        "Precinct":"243",
        "Votes":"1123"
    },
    {
        "Party":"REP",
        "Precinct":"245",
        "Votes":"494"
    },
    {
        "Party":"DEM",
        "Precinct":"245",
        "Votes":"799"
    },
    {
        "Party":"REP",
        "Precinct":"247",
        "Votes":"89"
    },
    {
        "Party":"DEM",
        "Precinct":"247",
        "Votes":"326"
    },
    {
        "Party":"REP",
        "Precinct":"248",
        "Votes":"8"
    },
    {
        "Party":"DEM",
        "Precinct":"248",
        "Votes":"38"
    },
    {
        "Party":"REP",
        "Precinct":"249",
        "Votes":"1020"
    },
    {
        "Party":"DEM",
        "Precinct":"249",
        "Votes":"1035"
    },
    {
        "Party":"REP",
        "Precinct":"250",
        "Votes":"23"
    },
    {
        "Party":"DEM",
        "Precinct":"250",
        "Votes":"26"
    },
    {
        "Party":"REP",
        "Precinct":"301",
        "Votes":"158"
    },
    {
        "Party":"DEM",
        "Precinct":"301",
        "Votes":"377"
    },
    {
        "Party":"REP",
        "Precinct":"303",
        "Votes":"8"
    },
    {
        "Party":"DEM",
        "Precinct":"303",
        "Votes":"362"
    },
    {
        "Party":"REP",
        "Precinct":"305",
        "Votes":"206"
    },
    {
        "Party":"DEM",
        "Precinct":"305",
        "Votes":"2469"
    },
    {
        "Party":"REP",
        "Precinct":"307",
        "Votes":"152"
    },
    {
        "Party":"DEM",
        "Precinct":"307",
        "Votes":"1458"
    },
    {
        "Party":"REP",
        "Precinct":"309",
        "Votes":"33"
    },
    {
        "Party":"DEM",
        "Precinct":"309",
        "Votes":"2000"
    },
    {
        "Party":"REP",
        "Precinct":"317",
        "Votes":"179"
    },
    {
        "Party":"DEM",
        "Precinct":"317",
        "Votes":"1270"
    },
    {
        "Party":"REP",
        "Precinct":"318",
        "Votes":"224"
    },
    {
        "Party":"DEM",
        "Precinct":"318",
        "Votes":"804"
    },
    {
        "Party":"REP",
        "Precinct":"319",
        "Votes":"186"
    },
    {
        "Party":"DEM",
        "Precinct":"319",
        "Votes":"980"
    },
    {
        "Party":"REP",
        "Precinct":"321",
        "Votes":"60"
    },
    {
        "Party":"DEM",
        "Precinct":"321",
        "Votes":"2227"
    },
    {
        "Party":"REP",
        "Precinct":"325",
        "Votes":"38"
    },
    {
        "Party":"DEM",
        "Precinct":"325",
        "Votes":"2356"
    },
    {
        "Party":"REP",
        "Precinct":"327",
        "Votes":"100"
    },
    {
        "Party":"DEM",
        "Precinct":"327",
        "Votes":"2312"
    },
    {
        "Party":"REP",
        "Precinct":"329",
        "Votes":"207"
    },
    {
        "Party":"DEM",
        "Precinct":"329",
        "Votes":"2374"
    },
    {
        "Party":"REP",
        "Precinct":"333",
        "Votes":"262"
    },
    {
        "Party":"DEM",
        "Precinct":"333",
        "Votes":"627"
    },
    {
        "Party":"REP",
        "Precinct":"335",
        "Votes":"344"
    },
    {
        "Party":"DEM",
        "Precinct":"335",
        "Votes":"1100"
    },
    {
        "Party":"REP",
        "Precinct":"338",
        "Votes":"118"
    },
    {
        "Party":"DEM",
        "Precinct":"338",
        "Votes":"951"
    },
    {
        "Party":"REP",
        "Precinct":"339",
        "Votes":"202"
    },
    {
        "Party":"DEM",
        "Precinct":"339",
        "Votes":"774"
    },
    {
        "Party":"REP",
        "Precinct":"341",
        "Votes":"405"
    },
    {
        "Party":"DEM",
        "Precinct":"341",
        "Votes":"2038"
    },
    {
        "Party":"REP",
        "Precinct":"342",
        "Votes":"407"
    },
    {
        "Party":"DEM",
        "Precinct":"342",
        "Votes":"1525"
    },
    {
        "Party":"REP",
        "Precinct":"343",
        "Votes":"287"
    },
    {
        "Party":"DEM",
        "Precinct":"343",
        "Votes":"782"
    },
    {
        "Party":"REP",
        "Precinct":"344",
        "Votes":"197"
    },
    {
        "Party":"DEM",
        "Precinct":"344",
        "Votes":"1585"
    },
    {
        "Party":"REP",
        "Precinct":"345",
        "Votes":"457"
    },
    {
        "Party":"DEM",
        "Precinct":"345",
        "Votes":"1464"
    },
    {
        "Party":"REP",
        "Precinct":"346",
        "Votes":"8"
    },
    {
        "Party":"DEM",
        "Precinct":"346",
        "Votes":"24"
    },
    {
        "Party":"REP",
        "Precinct":"347",
        "Votes":"306"
    },
    {
        "Party":"DEM",
        "Precinct":"347",
        "Votes":"1719"
    },
    {
        "Party":"REP",
        "Precinct":"353",
        "Votes":"342"
    },
    {
        "Party":"DEM",
        "Precinct":"353",
        "Votes":"809"
    },
    {
        "Party":"REP",
        "Precinct":"355",
        "Votes":"18"
    },
    {
        "Party":"DEM",
        "Precinct":"355",
        "Votes":"24"
    },
    {
        "Party":"REP",
        "Precinct":"356",
        "Votes":"62"
    },
    {
        "Party":"DEM",
        "Precinct":"356",
        "Votes":"221"
    },
    {
        "Party":"REP",
        "Precinct":"357",
        "Votes":"733"
    },
    {
        "Party":"DEM",
        "Precinct":"357",
        "Votes":"700"
    },
    {
        "Party":"REP",
        "Precinct":"358",
        "Votes":"623"
    },
    {
        "Party":"DEM",
        "Precinct":"358",
        "Votes":"792"
    },
    {
        "Party":"REP",
        "Precinct":"359",
        "Votes":"1710"
    },
    {
        "Party":"DEM",
        "Precinct":"359",
        "Votes":"2324"
    },
    {
        "Party":"REP",
        "Precinct":"361",
        "Votes":"1381"
    },
    {
        "Party":"DEM",
        "Precinct":"361",
        "Votes":"1076"
    },
    {
        "Party":"REP",
        "Precinct":"363",
        "Votes":"2375"
    },
    {
        "Party":"DEM",
        "Precinct":"363",
        "Votes":"3246"
    },
    {
        "Party":"REP",
        "Precinct":"367",
        "Votes":"2302"
    },
    {
        "Party":"DEM",
        "Precinct":"367",
        "Votes":"2962"
    },
    {
        "Party":"REP",
        "Precinct":"401",
        "Votes":"1293"
    },
    {
        "Party":"DEM",
        "Precinct":"401",
        "Votes":"1134"
    },
    {
        "Party":"REP",
        "Precinct":"403",
        "Votes":"632"
    },
    {
        "Party":"DEM",
        "Precinct":"403",
        "Votes":"1273"
    },
    {
        "Party":"REP",
        "Precinct":"404",
        "Votes":"487"
    },
    {
        "Party":"DEM",
        "Precinct":"404",
        "Votes":"325"
    },
    {
        "Party":"REP",
        "Precinct":"405",
        "Votes":"289"
    },
    {
        "Party":"DEM",
        "Precinct":"405",
        "Votes":"751"
    },
    {
        "Party":"REP",
        "Precinct":"407",
        "Votes":"599"
    },
    {
        "Party":"DEM",
        "Precinct":"407",
        "Votes":"1282"
    },
    {
        "Party":"REP",
        "Precinct":"410",
        "Votes":"360"
    },
    {
        "Party":"DEM",
        "Precinct":"410",
        "Votes":"774"
    },
    {
        "Party":"REP",
        "Precinct":"411",
        "Votes":"695"
    },
    {
        "Party":"DEM",
        "Precinct":"411",
        "Votes":"1096"
    },
    {
        "Party":"REP",
        "Precinct":"412",
        "Votes":"1215"
    },
    {
        "Party":"DEM",
        "Precinct":"412",
        "Votes":"1035"
    },
    {
        "Party":"REP",
        "Precinct":"413",
        "Votes":"395"
    },
    {
        "Party":"DEM",
        "Precinct":"413",
        "Votes":"497"
    },
    {
        "Party":"REP",
        "Precinct":"414",
        "Votes":"559"
    },
    {
        "Party":"DEM",
        "Precinct":"414",
        "Votes":"1744"
    },
    {
        "Party":"REP",
        "Precinct":"415",
        "Votes":"992"
    },
    {
        "Party":"DEM",
        "Precinct":"415",
        "Votes":"1289"
    },
    {
        "Party":"REP",
        "Precinct":"421",
        "Votes":"799"
    },
    {
        "Party":"DEM",
        "Precinct":"421",
        "Votes":"1100"
    },
    {
        "Party":"REP",
        "Precinct":"422",
        "Votes":"617"
    },
    {
        "Party":"DEM",
        "Precinct":"422",
        "Votes":"1198"
    },
    {
        "Party":"REP",
        "Precinct":"423",
        "Votes":"514"
    },
    {
        "Party":"DEM",
        "Precinct":"423",
        "Votes":"1024"
    },
    {
        "Party":"REP",
        "Precinct":"429",
        "Votes":"733"
    },
    {
        "Party":"DEM",
        "Precinct":"429",
        "Votes":"1189"
    },
    {
        "Party":"REP",
        "Precinct":"430",
        "Votes":"248"
    },
    {
        "Party":"DEM",
        "Precinct":"430",
        "Votes":"468"
    },
    {
        "Party":"REP",
        "Precinct":"431",
        "Votes":"1212"
    },
    {
        "Party":"DEM",
        "Precinct":"431",
        "Votes":"1198"
    },
    {
        "Party":"REP",
        "Precinct":"433",
        "Votes":"503"
    },
    {
        "Party":"DEM",
        "Precinct":"433",
        "Votes":"368"
    },
    {
        "Party":"REP",
        "Precinct":"434",
        "Votes":"973"
    },
    {
        "Party":"DEM",
        "Precinct":"434",
        "Votes":"1164"
    },
    {
        "Party":"REP",
        "Precinct":"451",
        "Votes":"857"
    },
    {
        "Party":"DEM",
        "Precinct":"451",
        "Votes":"1299"
    },
    {
        "Party":"REP",
        "Precinct":"454",
        "Votes":"599"
    },
    {
        "Party":"DEM",
        "Precinct":"454",
        "Votes":"1072"
    },
    {
        "Party":"REP",
        "Precinct":"455",
        "Votes":"483"
    },
    {
        "Party":"DEM",
        "Precinct":"455",
        "Votes":"820"
    },
    {
        "Party":"REP",
        "Precinct":"457",
        "Votes":"619"
    },
    {
        "Party":"DEM",
        "Precinct":"457",
        "Votes":"1064"
    },
    {
        "Party":"REP",
        "Precinct":"459",
        "Votes":"826"
    },
    {
        "Party":"DEM",
        "Precinct":"459",
        "Votes":"1576"
    },
    {
        "Party":"REP",
        "Precinct":"461",
        "Votes":"456"
    },
    {
        "Party":"DEM",
        "Precinct":"461",
        "Votes":"550"
    },
    {
        "Party":"REP",
        "Precinct":"463",
        "Votes":"283"
    },
    {
        "Party":"DEM",
        "Precinct":"463",
        "Votes":"946"
    },
    {
        "Party":"REP",
        "Precinct":"500",
        "Votes":"2212"
    },
    {
        "Party":"DEM",
        "Precinct":"500",
        "Votes":"1396"
    },
    {
        "Party":"REP",
        "Precinct":"501",
        "Votes":"1419"
    },
    {
        "Party":"DEM",
        "Precinct":"501",
        "Votes":"1294"
    },
    {
        "Party":"REP",
        "Precinct":"502",
        "Votes":"342"
    },
    {
        "Party":"DEM",
        "Precinct":"502",
        "Votes":"467"
    },
    {
        "Party":"REP",
        "Precinct":"503",
        "Votes":"973"
    },
    {
        "Party":"DEM",
        "Precinct":"503",
        "Votes":"1540"
    },
    {
        "Party":"REP",
        "Precinct":"504",
        "Votes":"693"
    },
    {
        "Party":"DEM",
        "Precinct":"504",
        "Votes":"1469"
    },
    {
        "Party":"REP",
        "Precinct":"505",
        "Votes":"1062"
    },
    {
        "Party":"DEM",
        "Precinct":"505",
        "Votes":"1588"
    },
    {
        "Party":"REP",
        "Precinct":"507",
        "Votes":"491"
    },
    {
        "Party":"DEM",
        "Precinct":"507",
        "Votes":"671"
    },
    {
        "Party":"REP",
        "Precinct":"508",
        "Votes":"1374"
    },
    {
        "Party":"DEM",
        "Precinct":"508",
        "Votes":"966"
    },
    {
        "Party":"REP",
        "Precinct":"509",
        "Votes":"710"
    },
    {
        "Party":"DEM",
        "Precinct":"509",
        "Votes":"611"
    },
    {
        "Party":"REP",
        "Precinct":"510",
        "Votes":"1149"
    },
    {
        "Party":"DEM",
        "Precinct":"510",
        "Votes":"732"
    },
    {
        "Party":"REP",
        "Precinct":"511",
        "Votes":"871"
    },
    {
        "Party":"DEM",
        "Precinct":"511",
        "Votes":"1156"
    },
    {
        "Party":"REP",
        "Precinct":"513",
        "Votes":"471"
    },
    {
        "Party":"DEM",
        "Precinct":"513",
        "Votes":"268"
    },
    {
        "Party":"REP",
        "Precinct":"514",
        "Votes":"793"
    },
    {
        "Party":"DEM",
        "Precinct":"514",
        "Votes":"531"
    },
    {
        "Party":"REP",
        "Precinct":"515",
        "Votes":"122"
    },
    {
        "Party":"DEM",
        "Precinct":"515",
        "Votes":"137"
    },
    {
        "Party":"REP",
        "Precinct":"516",
        "Votes":"1011"
    },
    {
        "Party":"DEM",
        "Precinct":"516",
        "Votes":"813"
    },
    {
        "Party":"REP",
        "Precinct":"517",
        "Votes":"782"
    },
    {
        "Party":"DEM",
        "Precinct":"517",
        "Votes":"602"
    },
    {
        "Party":"REP",
        "Precinct":"518",
        "Votes":"28"
    },
    {
        "Party":"DEM",
        "Precinct":"518",
        "Votes":"39"
    },
    {
        "Party":"REP",
        "Precinct":"519",
        "Votes":"835"
    },
    {
        "Party":"DEM",
        "Precinct":"519",
        "Votes":"852"
    },
    {
        "Party":"REP",
        "Precinct":"520",
        "Votes":"401"
    },
    {
        "Party":"DEM",
        "Precinct":"520",
        "Votes":"423"
    },
    {
        "Party":"REP",
        "Precinct":"521",
        "Votes":"1049"
    },
    {
        "Party":"DEM",
        "Precinct":"521",
        "Votes":"959"
    },
    {
        "Party":"REP",
        "Precinct":"522",
        "Votes":"496"
    },
    {
        "Party":"DEM",
        "Precinct":"522",
        "Votes":"419"
    },
    {
        "Party":"REP",
        "Precinct":"523",
        "Votes":"1068"
    },
    {
        "Party":"DEM",
        "Precinct":"523",
        "Votes":"1131"
    },
    {
        "Party":"REP",
        "Precinct":"524",
        "Votes":"518"
    },
    {
        "Party":"DEM",
        "Precinct":"524",
        "Votes":"669"
    },
    {
        "Party":"REP",
        "Precinct":"525",
        "Votes":"1522"
    },
    {
        "Party":"DEM",
        "Precinct":"525",
        "Votes":"1137"
    },
    {
        "Party":"REP",
        "Precinct":"526",
        "Votes":"934"
    },
    {
        "Party":"DEM",
        "Precinct":"526",
        "Votes":"534"
    },
    {
        "Party":"REP",
        "Precinct":"527",
        "Votes":"2259"
    },
    {
        "Party":"DEM",
        "Precinct":"527",
        "Votes":"1391"
    },
    {
        "Party":"REP",
        "Precinct":"528",
        "Votes":"1835"
    },
    {
        "Party":"DEM",
        "Precinct":"528",
        "Votes":"764"
    },
    {
        "Party":"REP",
        "Precinct":"529",
        "Votes":"1661"
    },
    {
        "Party":"DEM",
        "Precinct":"529",
        "Votes":"949"
    },
    {
        "Party":"REP",
        "Precinct":"530",
        "Votes":"779"
    },
    {
        "Party":"DEM",
        "Precinct":"530",
        "Votes":"325"
    },
    {
        "Party":"REP",
        "Precinct":"531",
        "Votes":"1786"
    },
    {
        "Party":"DEM",
        "Precinct":"531",
        "Votes":"954"
    },
    {
        "Party":"REP",
        "Precinct":"533",
        "Votes":"1384"
    },
    {
        "Party":"DEM",
        "Precinct":"533",
        "Votes":"1151"
    },
    {
        "Party":"REP",
        "Precinct":"534",
        "Votes":"755"
    },
    {
        "Party":"DEM",
        "Precinct":"534",
        "Votes":"1040"
    },
    {
        "Party":"REP",
        "Precinct":"535",
        "Votes":"557"
    },
    {
        "Party":"DEM",
        "Precinct":"535",
        "Votes":"783"
    },
    {
        "Party":"REP",
        "Precinct":"537",
        "Votes":"1530"
    },
    {
        "Party":"DEM",
        "Precinct":"537",
        "Votes":"1076"
    },
    {
        "Party":"REP",
        "Precinct":"538",
        "Votes":"1837"
    },
    {
        "Party":"DEM",
        "Precinct":"538",
        "Votes":"935"
    },
    {
        "Party":"REP",
        "Precinct":"550",
        "Votes":"505"
    },
    {
        "Party":"DEM",
        "Precinct":"550",
        "Votes":"258"
    },
    {
        "Party":"REP",
        "Precinct":"551",
        "Votes":"1062"
    },
    {
        "Party":"DEM",
        "Precinct":"551",
        "Votes":"565"
    },
    {
        "Party":"REP",
        "Precinct":"552",
        "Votes":"763"
    },
    {
        "Party":"DEM",
        "Precinct":"552",
        "Votes":"655"
    },
    {
        "Party":"REP",
        "Precinct":"554",
        "Votes":"574"
    },
    {
        "Party":"DEM",
        "Precinct":"554",
        "Votes":"370"
    },
    {
        "Party":"REP",
        "Precinct":"555",
        "Votes":"399"
    },
    {
        "Party":"DEM",
        "Precinct":"555",
        "Votes":"376"
    },
    {
        "Party":"REP",
        "Precinct":"556",
        "Votes":"51"
    },
    {
        "Party":"DEM",
        "Precinct":"556",
        "Votes":"133"
    },
    {
        "Party":"REP",
        "Precinct":"557",
        "Votes":"397"
    },
    {
        "Party":"DEM",
        "Precinct":"557",
        "Votes":"370"
    },
    {
        "Party":"REP",
        "Precinct":"558",
        "Votes":"173"
    },
    {
        "Party":"DEM",
        "Precinct":"558",
        "Votes":"226"
    },
    {
        "Party":"REP",
        "Precinct":"559",
        "Votes":"137"
    },
    {
        "Party":"DEM",
        "Precinct":"559",
        "Votes":"1080"
    },
    {
        "Party":"REP",
        "Precinct":"560",
        "Votes":"237"
    },
    {
        "Party":"DEM",
        "Precinct":"560",
        "Votes":"171"
    },
    {
        "Party":"REP",
        "Precinct":"561",
        "Votes":"134"
    },
    {
        "Party":"DEM",
        "Precinct":"561",
        "Votes":"102"
    },
    {
        "Party":"REP",
        "Precinct":"562",
        "Votes":"462"
    },
    {
        "Party":"DEM",
        "Precinct":"562",
        "Votes":"2121"
    },
    {
        "Party":"REP",
        "Precinct":"563",
        "Votes":"228"
    },
    {
        "Party":"DEM",
        "Precinct":"563",
        "Votes":"1399"
    },
    {
        "Party":"REP",
        "Precinct":"564",
        "Votes":"6"
    },
    {
        "Party":"DEM",
        "Precinct":"564",
        "Votes":"74"
    },
    {
        "Party":"REP",
        "Precinct":"565",
        "Votes":"47"
    },
    {
        "Party":"DEM",
        "Precinct":"565",
        "Votes":"135"
    },
    {
        "Party":"REP",
        "Precinct":"566",
        "Votes":"97"
    },
    {
        "Party":"DEM",
        "Precinct":"566",
        "Votes":"1276"
    },
    {
        "Party":"REP",
        "Precinct":"567",
        "Votes":"69"
    },
    {
        "Party":"DEM",
        "Precinct":"567",
        "Votes":"691"
    },
    {
        "Party":"REP",
        "Precinct":"569",
        "Votes":"866"
    },
    {
        "Party":"DEM",
        "Precinct":"569",
        "Votes":"942"
    },
    {
        "Party":"REP",
        "Precinct":"570",
        "Votes":"31"
    },
    {
        "Party":"DEM",
        "Precinct":"570",
        "Votes":"44"
    },
    {
        "Party":"REP",
        "Precinct":"571",
        "Votes":"500"
    },
    {
        "Party":"DEM",
        "Precinct":"571",
        "Votes":"633"
    },
    {
        "Party":"REP",
        "Precinct":"573",
        "Votes":"50"
    },
    {
        "Party":"DEM",
        "Precinct":"573",
        "Votes":"123"
    },
    {
        "Party":"REP",
        "Precinct":"574",
        "Votes":"924"
    },
    {
        "Party":"DEM",
        "Precinct":"574",
        "Votes":"818"
    },
    {
        "Party":"REP",
        "Precinct":"575",
        "Votes":"1037"
    },
    {
        "Party":"DEM",
        "Precinct":"575",
        "Votes":"735"
    },
    {
        "Party":"REP",
        "Precinct":"577",
        "Votes":"1319"
    },
    {
        "Party":"DEM",
        "Precinct":"577",
        "Votes":"1402"
    },
    {
        "Party":"REP",
        "Precinct":"578",
        "Votes":"735"
    },
    {
        "Party":"DEM",
        "Precinct":"578",
        "Votes":"539"
    },
    {
        "Party":"REP",
        "Precinct":"579",
        "Votes":"1226"
    },
    {
        "Party":"DEM",
        "Precinct":"579",
        "Votes":"593"
    },
    {
        "Party":"REP",
        "Precinct":"581",
        "Votes":"593"
    },
    {
        "Party":"DEM",
        "Precinct":"581",
        "Votes":"857"
    },
    {
        "Party":"REP",
        "Precinct":"583",
        "Votes":"425"
    },
    {
        "Party":"DEM",
        "Precinct":"583",
        "Votes":"753"
    },
    {
        "Party":"REP",
        "Precinct":"584",
        "Votes":"260"
    },
    {
        "Party":"DEM",
        "Precinct":"584",
        "Votes":"693"
    },
    {
        "Party":"REP",
        "Precinct":"585",
        "Votes":"1037"
    },
    {
        "Party":"DEM",
        "Precinct":"585",
        "Votes":"724"
    },
    {
        "Party":"REP",
        "Precinct":"587",
        "Votes":"1271"
    },
    {
        "Party":"DEM",
        "Precinct":"587",
        "Votes":"706"
    },
    {
        "Party":"REP",
        "Precinct":"589",
        "Votes":"540"
    },
    {
        "Party":"DEM",
        "Precinct":"589",
        "Votes":"256"
    },
    {
        "Party":"REP",
        "Precinct":"591",
        "Votes":"1725"
    },
    {
        "Party":"DEM",
        "Precinct":"591",
        "Votes":"938"
    },
    {
        "Party":"REP",
        "Precinct":"595",
        "Votes":"1313"
    },
    {
        "Party":"DEM",
        "Precinct":"595",
        "Votes":"740"
    },
    {
        "Party":"REP",
        "Precinct":"601",
        "Votes":"136"
    },
    {
        "Party":"DEM",
        "Precinct":"601",
        "Votes":"921"
    },
    {
        "Party":"REP",
        "Precinct":"603",
        "Votes":"109"
    },
    {
        "Party":"DEM",
        "Precinct":"603",
        "Votes":"202"
    },
    {
        "Party":"REP",
        "Precinct":"605",
        "Votes":"172"
    },
    {
        "Party":"DEM",
        "Precinct":"605",
        "Votes":"233"
    },
    {
        "Party":"REP",
        "Precinct":"613",
        "Votes":"136"
    },
    {
        "Party":"DEM",
        "Precinct":"613",
        "Votes":"1289"
    },
    {
        "Party":"REP",
        "Precinct":"617",
        "Votes":"246"
    },
    {
        "Party":"DEM",
        "Precinct":"617",
        "Votes":"1725"
    },
    {
        "Party":"REP",
        "Precinct":"622",
        "Votes":"223"
    },
    {
        "Party":"DEM",
        "Precinct":"622",
        "Votes":"615"
    },
    {
        "Party":"REP",
        "Precinct":"623",
        "Votes":"288"
    },
    {
        "Party":"DEM",
        "Precinct":"623",
        "Votes":"727"
    },
    {
        "Party":"REP",
        "Precinct":"625",
        "Votes":"307"
    },
    {
        "Party":"DEM",
        "Precinct":"625",
        "Votes":"386"
    },
    {
        "Party":"REP",
        "Precinct":"626",
        "Votes":"203"
    },
    {
        "Party":"DEM",
        "Precinct":"626",
        "Votes":"461"
    },
    {
        "Party":"REP",
        "Precinct":"629",
        "Votes":"606"
    },
    {
        "Party":"DEM",
        "Precinct":"629",
        "Votes":"882"
    },
    {
        "Party":"REP",
        "Precinct":"631",
        "Votes":"491"
    },
    {
        "Party":"DEM",
        "Precinct":"631",
        "Votes":"381"
    },
    {
        "Party":"REP",
        "Precinct":"633",
        "Votes":"893"
    },
    {
        "Party":"DEM",
        "Precinct":"633",
        "Votes":"478"
    },
    {
        "Party":"REP",
        "Precinct":"635",
        "Votes":"527"
    },
    {
        "Party":"DEM",
        "Precinct":"635",
        "Votes":"838"
    },
    {
        "Party":"REP",
        "Precinct":"636",
        "Votes":"210"
    },
    {
        "Party":"DEM",
        "Precinct":"636",
        "Votes":"156"
    },
    {
        "Party":"REP",
        "Precinct":"637",
        "Votes":"11"
    },
    {
        "Party":"DEM",
        "Precinct":"637",
        "Votes":"32"
    },
    {
        "Party":"REP",
        "Precinct":"639",
        "Votes":"453"
    },
    {
        "Party":"DEM",
        "Precinct":"639",
        "Votes":"198"
    },
    {
        "Party":"REP",
        "Precinct":"641",
        "Votes":"211"
    },
    {
        "Party":"DEM",
        "Precinct":"641",
        "Votes":"724"
    },
    {
        "Party":"REP",
        "Precinct":"643",
        "Votes":"93"
    },
    {
        "Party":"DEM",
        "Precinct":"643",
        "Votes":"341"
    },
    {
        "Party":"REP",
        "Precinct":"650",
        "Votes":"147"
    },
    {
        "Party":"DEM",
        "Precinct":"650",
        "Votes":"674"
    },
    {
        "Party":"REP",
        "Precinct":"651",
        "Votes":"612"
    },
    {
        "Party":"DEM",
        "Precinct":"651",
        "Votes":"610"
    },
    {
        "Party":"REP",
        "Precinct":"652",
        "Votes":"399"
    },
    {
        "Party":"DEM",
        "Precinct":"652",
        "Votes":"686"
    },
    {
        "Party":"REP",
        "Precinct":"653",
        "Votes":"804"
    },
    {
        "Party":"DEM",
        "Precinct":"653",
        "Votes":"738"
    },
    {
        "Party":"REP",
        "Precinct":"654",
        "Votes":"165"
    },
    {
        "Party":"DEM",
        "Precinct":"654",
        "Votes":"579"
    },
    {
        "Party":"REP",
        "Precinct":"655",
        "Votes":"764"
    },
    {
        "Party":"DEM",
        "Precinct":"655",
        "Votes":"804"
    },
    {
        "Party":"REP",
        "Precinct":"657",
        "Votes":"520"
    },
    {
        "Party":"DEM",
        "Precinct":"657",
        "Votes":"649"
    },
    {
        "Party":"REP",
        "Precinct":"658",
        "Votes":"233"
    },
    {
        "Party":"DEM",
        "Precinct":"658",
        "Votes":"431"
    },
    {
        "Party":"REP",
        "Precinct":"659",
        "Votes":"662"
    },
    {
        "Party":"DEM",
        "Precinct":"659",
        "Votes":"655"
    },
    {
        "Party":"REP",
        "Precinct":"660",
        "Votes":"31"
    },
    {
        "Party":"DEM",
        "Precinct":"660",
        "Votes":"121"
    },
    {
        "Party":"REP",
        "Precinct":"661",
        "Votes":"455"
    },
    {
        "Party":"DEM",
        "Precinct":"661",
        "Votes":"723"
    },
    {
        "Party":"REP",
        "Precinct":"662",
        "Votes":"203"
    },
    {
        "Party":"DEM",
        "Precinct":"662",
        "Votes":"285"
    },
    {
        "Party":"REP",
        "Precinct":"671",
        "Votes":"1793"
    },
    {
        "Party":"DEM",
        "Precinct":"671",
        "Votes":"2143"
    },
    {
        "Party":"REP",
        "Precinct":"673",
        "Votes":"888"
    },
    {
        "Party":"DEM",
        "Precinct":"673",
        "Votes":"1421"
    },
    {
        "Party":"REP",
        "Precinct":"701",
        "Votes":"4625"
    },
    {
        "Party":"DEM",
        "Precinct":"701",
        "Votes":"2296"
    },
    {
        "Party":"REP",
        "Precinct":"703",
        "Votes":"908"
    },
    {
        "Party":"DEM",
        "Precinct":"703",
        "Votes":"282"
    },
    {
        "Party":"REP",
        "Precinct":"705",
        "Votes":"434"
    },
    {
        "Party":"DEM",
        "Precinct":"705",
        "Votes":"109"
    },
    {
        "Party":"REP",
        "Precinct":"706",
        "Votes":"677"
    },
    {
        "Party":"DEM",
        "Precinct":"706",
        "Votes":"230"
    },
    {
        "Party":"REP",
        "Precinct":"707",
        "Votes":"565"
    },
    {
        "Party":"DEM",
        "Precinct":"707",
        "Votes":"189"
    },
    {
        "Party":"REP",
        "Precinct":"708",
        "Votes":"95"
    },
    {
        "Party":"DEM",
        "Precinct":"708",
        "Votes":"70"
    },
    {
        "Party":"REP",
        "Precinct":"709",
        "Votes":"886"
    },
    {
        "Party":"DEM",
        "Precinct":"709",
        "Votes":"374"
    },
    {
        "Party":"REP",
        "Precinct":"711",
        "Votes":"476"
    },
    {
        "Party":"DEM",
        "Precinct":"711",
        "Votes":"146"
    },
    {
        "Party":"REP",
        "Precinct":"712",
        "Votes":"141"
    },
    {
        "Party":"DEM",
        "Precinct":"712",
        "Votes":"43"
    },
    {
        "Party":"REP",
        "Precinct":"713",
        "Votes":"520"
    },
    {
        "Party":"DEM",
        "Precinct":"713",
        "Votes":"756"
    },
    {
        "Party":"REP",
        "Precinct":"715",
        "Votes":"82"
    },
    {
        "Party":"DEM",
        "Precinct":"715",
        "Votes":"100"
    },
    {
        "Party":"REP",
        "Precinct":"721",
        "Votes":"1209"
    },
    {
        "Party":"DEM",
        "Precinct":"721",
        "Votes":"644"
    },
    {
        "Party":"REP",
        "Precinct":"750",
        "Votes":"1305"
    },
    {
        "Party":"DEM",
        "Precinct":"750",
        "Votes":"671"
    },
    {
        "Party":"REP",
        "Precinct":"751",
        "Votes":"1577"
    },
    {
        "Party":"DEM",
        "Precinct":"751",
        "Votes":"690"
    },
    {
        "Party":"REP",
        "Precinct":"753",
        "Votes":"405"
    },
    {
        "Party":"DEM",
        "Precinct":"753",
        "Votes":"1663"
    },
    {
        "Party":"REP",
        "Precinct":"754",
        "Votes":"787"
    },
    {
        "Party":"DEM",
        "Precinct":"754",
        "Votes":"429"
    },
    {
        "Party":"REP",
        "Precinct":"755",
        "Votes":"401"
    },
    {
        "Party":"DEM",
        "Precinct":"755",
        "Votes":"316"
    },
    {
        "Party":"REP",
        "Precinct":"757",
        "Votes":"1077"
    },
    {
        "Party":"DEM",
        "Precinct":"757",
        "Votes":"1188"
    },
    {
        "Party":"REP",
        "Precinct":"759",
        "Votes":"1331"
    },
    {
        "Party":"DEM",
        "Precinct":"759",
        "Votes":"835"
    },
    {
        "Party":"REP",
        "Precinct":"761",
        "Votes":"1716"
    },
    {
        "Party":"DEM",
        "Precinct":"761",
        "Votes":"535"
    },
    {
        "Party":"REP",
        "Precinct":"763",
        "Votes":"314"
    },
    {
        "Party":"DEM",
        "Precinct":"763",
        "Votes":"168"
    },
    {
        "Party":"REP",
        "Precinct":"764",
        "Votes":"1027"
    },
    {
        "Party":"DEM",
        "Precinct":"764",
        "Votes":"476"
    },
    {
        "Party":"REP",
        "Precinct":"765",
        "Votes":"846"
    },
    {
        "Party":"DEM",
        "Precinct":"765",
        "Votes":"322"
    },
    {
        "Party":"REP",
        "Precinct":"767",
        "Votes":"889"
    },
    {
        "Party":"DEM",
        "Precinct":"767",
        "Votes":"566"
    },
    {
        "Party":"REP",
        "Precinct":"769",
        "Votes":"1066"
    },
    {
        "Party":"DEM",
        "Precinct":"769",
        "Votes":"311"
    },
    {
        "Party":"REP",
        "Precinct":"801",
        "Votes":"789"
    },
    {
        "Party":"DEM",
        "Precinct":"801",
        "Votes":"700"
    },
    {
        "Party":"REP",
        "Precinct":"803",
        "Votes":"431"
    },
    {
        "Party":"DEM",
        "Precinct":"803",
        "Votes":"279"
    },
    {
        "Party":"REP",
        "Precinct":"804",
        "Votes":"1397"
    },
    {
        "Party":"DEM",
        "Precinct":"804",
        "Votes":"917"
    },
    {
        "Party":"REP",
        "Precinct":"805",
        "Votes":"1730"
    },
    {
        "Party":"DEM",
        "Precinct":"805",
        "Votes":"1073"
    },
    {
        "Party":"REP",
        "Precinct":"806",
        "Votes":"1223"
    },
    {
        "Party":"DEM",
        "Precinct":"806",
        "Votes":"585"
    },
    {
        "Party":"REP",
        "Precinct":"807",
        "Votes":"746"
    },
    {
        "Party":"DEM",
        "Precinct":"807",
        "Votes":"426"
    },
    {
        "Party":"REP",
        "Precinct":"808",
        "Votes":"709"
    },
    {
        "Party":"DEM",
        "Precinct":"808",
        "Votes":"437"
    },
    {
        "Party":"REP",
        "Precinct":"809",
        "Votes":"449"
    },
    {
        "Party":"DEM",
        "Precinct":"809",
        "Votes":"294"
    },
    {
        "Party":"REP",
        "Precinct":"810",
        "Votes":"1044"
    },
    {
        "Party":"DEM",
        "Precinct":"810",
        "Votes":"589"
    },
    {
        "Party":"REP",
        "Precinct":"811",
        "Votes":"1237"
    },
    {
        "Party":"DEM",
        "Precinct":"811",
        "Votes":"726"
    },
    {
        "Party":"REP",
        "Precinct":"813",
        "Votes":"2141"
    },
    {
        "Party":"DEM",
        "Precinct":"813",
        "Votes":"1334"
    },
    {
        "Party":"REP",
        "Precinct":"814",
        "Votes":"1538"
    },
    {
        "Party":"DEM",
        "Precinct":"814",
        "Votes":"478"
    },
    {
        "Party":"REP",
        "Precinct":"815",
        "Votes":"583"
    },
    {
        "Party":"DEM",
        "Precinct":"815",
        "Votes":"268"
    },
    {
        "Party":"REP",
        "Precinct":"816",
        "Votes":"884"
    },
    {
        "Party":"DEM",
        "Precinct":"816",
        "Votes":"416"
    },
    {
        "Party":"REP",
        "Precinct":"817",
        "Votes":"1787"
    },
    {
        "Party":"DEM",
        "Precinct":"817",
        "Votes":"1015"
    },
    {
        "Party":"REP",
        "Precinct":"818",
        "Votes":"1166"
    },
    {
        "Party":"DEM",
        "Precinct":"818",
        "Votes":"923"
    },
    {
        "Party":"REP",
        "Precinct":"819",
        "Votes":"489"
    },
    {
        "Party":"DEM",
        "Precinct":"819",
        "Votes":"315"
    },
    {
        "Party":"REP",
        "Precinct":"820",
        "Votes":"1273"
    },
    {
        "Party":"DEM",
        "Precinct":"820",
        "Votes":"764"
    },
    {
        "Party":"REP",
        "Precinct":"821",
        "Votes":"1229"
    },
    {
        "Party":"DEM",
        "Precinct":"821",
        "Votes":"1204"
    },
    {
        "Party":"REP",
        "Precinct":"825",
        "Votes":"1071"
    },
    {
        "Party":"DEM",
        "Precinct":"825",
        "Votes":"819"
    },
    {
        "Party":"REP",
        "Precinct":"827",
        "Votes":"1060"
    },
    {
        "Party":"DEM",
        "Precinct":"827",
        "Votes":"791"
    },
    {
        "Party":"REP",
        "Precinct":"828",
        "Votes":"1776"
    },
    {
        "Party":"DEM",
        "Precinct":"828",
        "Votes":"2583"
    },
    {
        "Party":"REP",
        "Precinct":"829",
        "Votes":"1071"
    },
    {
        "Party":"DEM",
        "Precinct":"829",
        "Votes":"1204"
    },
    {
        "Party":"REP",
        "Precinct":"830",
        "Votes":"583"
    },
    {
        "Party":"DEM",
        "Precinct":"830",
        "Votes":"819"
    },
    {
        "Party":"REP",
        "Precinct":"832",
        "Votes":"878"
    },
    {
        "Party":"DEM",
        "Precinct":"832",
        "Votes":"1024"
    },
    {
        "Party":"REP",
        "Precinct":"833",
        "Votes":"491"
    },
    {
        "Party":"DEM",
        "Precinct":"833",
        "Votes":"750"
    },
    {
        "Party":"REP",
        "Precinct":"834",
        "Votes":"516"
    },
    {
        "Party":"DEM",
        "Precinct":"834",
        "Votes":"1030"
    },
    {
        "Party":"REP",
        "Precinct":"851",
        "Votes":"1013"
    },
    {
        "Party":"DEM",
        "Precinct":"851",
        "Votes":"1109"
    },
    {
        "Party":"REP",
        "Precinct":"852",
        "Votes":"623"
    },
    {
        "Party":"DEM",
        "Precinct":"852",
        "Votes":"1181"
    },
    {
        "Party":"REP",
        "Precinct":"853",
        "Votes":"169"
    },
    {
        "Party":"DEM",
        "Precinct":"853",
        "Votes":"561"
    },
    {
        "Party":"REP",
        "Precinct":"854",
        "Votes":"31"
    },
    {
        "Party":"DEM",
        "Precinct":"854",
        "Votes":"15"
    },
    {
        "Party":"REP",
        "Precinct":"855",
        "Votes":"1031"
    },
    {
        "Party":"DEM",
        "Precinct":"855",
        "Votes":"1046"
    },
    {
        "Party":"REP",
        "Precinct":"856",
        "Votes":"1449"
    },
    {
        "Party":"DEM",
        "Precinct":"856",
        "Votes":"884"
    },
    {
        "Party":"REP",
        "Precinct":"857",
        "Votes":"512"
    },
    {
        "Party":"DEM",
        "Precinct":"857",
        "Votes":"965"
    },
    {
        "Party":"REP",
        "Precinct":"858",
        "Votes":"171"
    },
    {
        "Party":"DEM",
        "Precinct":"858",
        "Votes":"303"
    },
    {
        "Party":"REP",
        "Precinct":"860",
        "Votes":"725"
    },
    {
        "Party":"DEM",
        "Precinct":"860",
        "Votes":"628"
    },
    {
        "Party":"REP",
        "Precinct":"862",
        "Votes":"103"
    },
    {
        "Party":"DEM",
        "Precinct":"862",
        "Votes":"41"
    },
    {
        "Party":"REP",
        "Precinct":"863",
        "Votes":"342"
    },
    {
        "Party":"DEM",
        "Precinct":"863",
        "Votes":"278"
    },
    {
        "Party":"REP",
        "Precinct":"867",
        "Votes":"1458"
    },
    {
        "Party":"DEM",
        "Precinct":"867",
        "Votes":"1344"
    },
    {
        "Party":"REP",
        "Precinct":"868",
        "Votes":"596"
    },
    {
        "Party":"DEM",
        "Precinct":"868",
        "Votes":"548"
    },
    {
        "Party":"REP",
        "Precinct":"869",
        "Votes":"1412"
    },
    {
        "Party":"DEM",
        "Precinct":"869",
        "Votes":"1176"
    },
    {
        "Party":"REP",
        "Precinct":"871",
        "Votes":"1195"
    },
    {
        "Party":"DEM",
        "Precinct":"871",
        "Votes":"949"
    },
    {
        "Party":"REP",
        "Precinct":"875",
        "Votes":"1296"
    },
    {
        "Party":"DEM",
        "Precinct":"875",
        "Votes":"1013"
    },
    {
        "Party":"REP",
        "Precinct":"879",
        "Votes":"1437"
    },
    {
        "Party":"DEM",
        "Precinct":"879",
        "Votes":"1482"
    },
    {
        "Party":"REP",
        "Precinct":"883",
        "Votes":"684"
    },
    {
        "Party":"DEM",
        "Precinct":"883",
        "Votes":"1163"
    },
    {
        "Party":"REP",
        "Precinct":"885",
        "Votes":"1052"
    },
    {
        "Party":"DEM",
        "Precinct":"885",
        "Votes":"1332"
    },
    {
        "Party":"REP",
        "Precinct":"887",
        "Votes":"843"
    },
    {
        "Party":"DEM",
        "Precinct":"887",
        "Votes":"952"
    },
    {
        "Party":"REP",
        "Precinct":"889",
        "Votes":"257"
    },
    {
        "Party":"DEM",
        "Precinct":"889",
        "Votes":"288"
    },
    {
        "Party":"REP",
        "Precinct":"891",
        "Votes":"1135"
    },
    {
        "Party":"DEM",
        "Precinct":"891",
        "Votes":"446"
    },
    {
        "Party":"REP",
        "Precinct":"892",
        "Votes":"832"
    },
    {
        "Party":"DEM",
        "Precinct":"892",
        "Votes":"295"
    },
    {
        "Party":"REP",
        "Precinct":"901",
        "Votes":"567"
    },
    {
        "Party":"DEM",
        "Precinct":"901",
        "Votes":"878"
    },
    {
        "Party":"REP",
        "Precinct":"904",
        "Votes":"1268"
    },
    {
        "Party":"DEM",
        "Precinct":"904",
        "Votes":"936"
    },
    {
        "Party":"REP",
        "Precinct":"905",
        "Votes":"216"
    },
    {
        "Party":"DEM",
        "Precinct":"905",
        "Votes":"119"
    },
    {
        "Party":"REP",
        "Precinct":"906",
        "Votes":"229"
    },
    {
        "Party":"DEM",
        "Precinct":"906",
        "Votes":"118"
    },
    {
        "Party":"REP",
        "Precinct":"907",
        "Votes":"576"
    },
    {
        "Party":"DEM",
        "Precinct":"907",
        "Votes":"277"
    },
    {
        "Party":"REP",
        "Precinct":"908",
        "Votes":"1658"
    },
    {
        "Party":"DEM",
        "Precinct":"908",
        "Votes":"1123"
    },
    {
        "Party":"REP",
        "Precinct":"909",
        "Votes":"1789"
    },
    {
        "Party":"DEM",
        "Precinct":"909",
        "Votes":"924"
    },
    {
        "Party":"REP",
        "Precinct":"912",
        "Votes":"516"
    },
    {
        "Party":"DEM",
        "Precinct":"912",
        "Votes":"361"
    },
    {
        "Party":"REP",
        "Precinct":"913",
        "Votes":"1068"
    },
    {
        "Party":"DEM",
        "Precinct":"913",
        "Votes":"1170"
    },
    {
        "Party":"REP",
        "Precinct":"917",
        "Votes":"169"
    },
    {
        "Party":"DEM",
        "Precinct":"917",
        "Votes":"84"
    },
    {
        "Party":"REP",
        "Precinct":"918",
        "Votes":"362"
    },
    {
        "Party":"DEM",
        "Precinct":"918",
        "Votes":"92"
    },
    {
        "Party":"REP",
        "Precinct":"919",
        "Votes":"648"
    },
    {
        "Party":"DEM",
        "Precinct":"919",
        "Votes":"587"
    },
    {
        "Party":"REP",
        "Precinct":"921",
        "Votes":"966"
    },
    {
        "Party":"DEM",
        "Precinct":"921",
        "Votes":"688"
    },
    {
        "Party":"REP",
        "Precinct":"925",
        "Votes":"495"
    },
    {
        "Party":"DEM",
        "Precinct":"925",
        "Votes":"320"
    },
    {
        "Party":"REP",
        "Precinct":"927",
        "Votes":"288"
    },
    {
        "Party":"DEM",
        "Precinct":"927",
        "Votes":"150"
    },
    {
        "Party":"REP",
        "Precinct":"929",
        "Votes":"1891"
    },
    {
        "Party":"DEM",
        "Precinct":"929",
        "Votes":"1334"
    },
    {
        "Party":"REP",
        "Precinct":"932",
        "Votes":"502"
    },
    {
        "Party":"DEM",
        "Precinct":"932",
        "Votes":"929"
    },
    {
        "Party":"REP",
        "Precinct":"933",
        "Votes":"991"
    },
    {
        "Party":"DEM",
        "Precinct":"933",
        "Votes":"963"
    },
    {
        "Party":"REP",
        "Precinct":"935",
        "Votes":"1634"
    },
    {
        "Party":"DEM",
        "Precinct":"935",
        "Votes":"1284"
    },
    {
        "Party":"REP",
        "Precinct":"937",
        "Votes":"1860"
    },
    {
        "Party":"DEM",
        "Precinct":"937",
        "Votes":"687"
    },
    {
        "Party":"REP",
        "Precinct":"939",
        "Votes":"1218"
    },
    {
        "Party":"DEM",
        "Precinct":"939",
        "Votes":"884"
    },
    {
        "Party":"REP",
        "Precinct":"940",
        "Votes":"111"
    },
    {
        "Party":"DEM",
        "Precinct":"940",
        "Votes":"95"
    },
    {
        "Party":"REP",
        "Precinct":"941",
        "Votes":"849"
    },
    {
        "Party":"DEM",
        "Precinct":"941",
        "Votes":"325"
    },
    {
        "Party":"REP",
        "Precinct":"942",
        "Votes":"776"
    },
    {
        "Party":"DEM",
        "Precinct":"942",
        "Votes":"1439"
    },
    {
        "Party":"REP",
        "Precinct":"943",
        "Votes":"336"
    },
    {
        "Party":"DEM",
        "Precinct":"943",
        "Votes":"345"
    },
    {
        "Party":"REP",
        "Precinct":"944",
        "Votes":"1357"
    },
    {
        "Party":"DEM",
        "Precinct":"944",
        "Votes":"1955"
    },
    {
        "Party":"REP",
        "Precinct":"945",
        "Votes":"602"
    },
    {
        "Party":"DEM",
        "Precinct":"945",
        "Votes":"389"
    },
    {
        "Party":"REP",
        "Precinct":"946",
        "Votes":"1132"
    },
    {
        "Party":"DEM",
        "Precinct":"946",
        "Votes":"1693"
    },
    {
        "Party":"REP",
        "Precinct":"947",
        "Votes":"2477"
    },
    {
        "Party":"DEM",
        "Precinct":"947",
        "Votes":"3075"
    },
    {
        "Party":"REP",
        "Precinct":"948",
        "Votes":"509"
    },
    {
        "Party":"DEM",
        "Precinct":"948",
        "Votes":"373"
    },
    {
        "Party":"REP",
        "Precinct":"949",
        "Votes":"2238"
    },
    {
        "Party":"DEM",
        "Precinct":"949",
        "Votes":"2231"
    },
    {
        "Party":"REP",
        "Precinct":"950",
        "Votes":"466"
    },
    {
        "Party":"DEM",
        "Precinct":"950",
        "Votes":"397"
    },
    {
        "Party":"REP",
        "Precinct":"951",
        "Votes":"1295"
    },
    {
        "Party":"DEM",
        "Precinct":"951",
        "Votes":"1208"
    },
    {
        "Party":"REP",
        "Precinct":"952",
        "Votes":"998"
    },
    {
        "Party":"DEM",
        "Precinct":"952",
        "Votes":"689"
    },
    {
        "Party":"REP",
        "Precinct":"953",
        "Votes":"1341"
    },
    {
        "Party":"DEM",
        "Precinct":"953",
        "Votes":"1125"
    },
    {
        "Party":"REP",
        "Precinct":"954",
        "Votes":"152"
    },
    {
        "Party":"DEM",
        "Precinct":"954",
        "Votes":"310"
    },
    {
        "Party":"REP",
        "Precinct":"955",
        "Votes":"1244"
    },
    {
        "Party":"DEM",
        "Precinct":"955",
        "Votes":"1374"
    },
    {
        "Party":"REP",
        "Precinct":"957",
        "Votes":"1229"
    },
    {
        "Party":"DEM",
        "Precinct":"957",
        "Votes":"1298"
    },
    {
        "Party":"REP",
        "Precinct":"958",
        "Votes":"73"
    },
    {
        "Party":"DEM",
        "Precinct":"958",
        "Votes":"38"
    },
    {
        "Party":"REP",
        "Precinct":"959",
        "Votes":"619"
    },
    {
        "Party":"DEM",
        "Precinct":"959",
        "Votes":"996"
    },
    {
        "Party":"REP",
        "Precinct":"961",
        "Votes":"270"
    },
    {
        "Party":"DEM",
        "Precinct":"961",
        "Votes":"319"
    },
    {
        "Party":"REP",
        "Precinct":"962",
        "Votes":"263"
    },
    {
        "Party":"DEM",
        "Precinct":"962",
        "Votes":"174"
    },
    {
        "Party":"REP",
        "Precinct":"963",
        "Votes":"15"
    },
    {
        "Party":"DEM",
        "Precinct":"963",
        "Votes":"9"
    },
    {
        "Party":"REP",
        "Precinct":"964",
        "Votes":"37"
    },
    {
        "Party":"DEM",
        "Precinct":"964",
        "Votes":"214"
    },
    {
        "Party":"REP",
        "Precinct":"965",
        "Votes":"80"
    },
    {
        "Party":"DEM",
        "Precinct":"965",
        "Votes":"1357"
    },
    {
        "Party":"REP",
        "Precinct":"967",
        "Votes":"150"
    },
    {
        "Party":"DEM",
        "Precinct":"967",
        "Votes":"852"
    },
    {
        "Party":"REP",
        "Precinct":"968",
        "Votes":"450"
    },
    {
        "Party":"DEM",
        "Precinct":"968",
        "Votes":"1202"
    },
    {
        "Party":"REP",
        "Precinct":"969",
        "Votes":"289"
    },
    {
        "Party":"DEM",
        "Precinct":"969",
        "Votes":"955"
    },
    {
        "Party":"REP",
        "Precinct":"971",
        "Votes":"353"
    },
    {
        "Party":"DEM",
        "Precinct":"971",
        "Votes":"1488"
    },
    {
        "Party":"REP",
        "Precinct":"972",
        "Votes":"206"
    },
    {
        "Party":"DEM",
        "Precinct":"972",
        "Votes":"257"
    },
    {
        "Party":"REP",
        "Precinct":"973",
        "Votes":"117"
    },
    {
        "Party":"DEM",
        "Precinct":"973",
        "Votes":"228"
    },
    {
        "Party":"REP",
        "Precinct":"999",
        "Votes":"666"
    },
    {
        "Party":"DEM",
        "Precinct":"999",
        "Votes":"454"
    }
]

module.exports=votes;