var votes= [
    {
        "Party":"REP",
        "Precinct":"101",
        "Votes":"528"
    },
    {
        "Party":"DEM",
        "Precinct":"101",
        "Votes":"2227"
    },
    {
        "Party":"REP",
        "Precinct":"102",
        "Votes":"226"
    },
    {
        "Party":"DEM",
        "Precinct":"102",
        "Votes":"1131"
    },
    {
        "Party":"REP",
        "Precinct":"103",
        "Votes":"187"
    },
    {
        "Party":"DEM",
        "Precinct":"103",
        "Votes":"381"
    },
    {
        "Party":"REP",
        "Precinct":"104",
        "Votes":"195"
    },
    {
        "Party":"DEM",
        "Precinct":"104",
        "Votes":"1108"
    },
    {
        "Party":"REP",
        "Precinct":"105",
        "Votes":"385"
    },
    {
        "Party":"DEM",
        "Precinct":"105",
        "Votes":"2302"
    },
    {
        "Party":"REP",
        "Precinct":"106",
        "Votes":"192"
    },
    {
        "Party":"DEM",
        "Precinct":"106",
        "Votes":"398"
    },
    {
        "Party":"REP",
        "Precinct":"107",
        "Votes":"464"
    },
    {
        "Party":"DEM",
        "Precinct":"107",
        "Votes":"981"
    },
    {
        "Party":"REP",
        "Precinct":"108",
        "Votes":"637"
    },
    {
        "Party":"DEM",
        "Precinct":"108",
        "Votes":"1369"
    },
    {
        "Party":"REP",
        "Precinct":"109",
        "Votes":"234"
    },
    {
        "Party":"DEM",
        "Precinct":"109",
        "Votes":"1378"
    },
    {
        "Party":"REP",
        "Precinct":"110",
        "Votes":"60"
    },
    {
        "Party":"DEM",
        "Precinct":"110",
        "Votes":"154"
    },
    {
        "Party":"REP",
        "Precinct":"111",
        "Votes":"121"
    },
    {
        "Party":"DEM",
        "Precinct":"111",
        "Votes":"320"
    },
    {
        "Party":"REP",
        "Precinct":"112",
        "Votes":"150"
    },
    {
        "Party":"DEM",
        "Precinct":"112",
        "Votes":"873"
    },
    {
        "Party":"REP",
        "Precinct":"113",
        "Votes":"35"
    },
    {
        "Party":"DEM",
        "Precinct":"113",
        "Votes":"1045"
    },
    {
        "Party":"REP",
        "Precinct":"114",
        "Votes":"29"
    },
    {
        "Party":"DEM",
        "Precinct":"114",
        "Votes":"864"
    },
    {
        "Party":"REP",
        "Precinct":"115",
        "Votes":"33"
    },
    {
        "Party":"DEM",
        "Precinct":"115",
        "Votes":"922"
    },
    {
        "Party":"REP",
        "Precinct":"116",
        "Votes":"91"
    },
    {
        "Party":"DEM",
        "Precinct":"116",
        "Votes":"990"
    },
    {
        "Party":"REP",
        "Precinct":"117",
        "Votes":"32"
    },
    {
        "Party":"DEM",
        "Precinct":"117",
        "Votes":"725"
    },
    {
        "Party":"REP",
        "Precinct":"118",
        "Votes":"260"
    },
    {
        "Party":"DEM",
        "Precinct":"118",
        "Votes":"717"
    },
    {
        "Party":"REP",
        "Precinct":"119",
        "Votes":"97"
    },
    {
        "Party":"DEM",
        "Precinct":"119",
        "Votes":"1502"
    },
    {
        "Party":"REP",
        "Precinct":"120",
        "Votes":"89"
    },
    {
        "Party":"DEM",
        "Precinct":"120",
        "Votes":"1848"
    },
    {
        "Party":"REP",
        "Precinct":"121",
        "Votes":"136"
    },
    {
        "Party":"DEM",
        "Precinct":"121",
        "Votes":"351"
    },
    {
        "Party":"REP",
        "Precinct":"122",
        "Votes":"61"
    },
    {
        "Party":"DEM",
        "Precinct":"122",
        "Votes":"129"
    },
    {
        "Party":"REP",
        "Precinct":"123",
        "Votes":"811"
    },
    {
        "Party":"DEM",
        "Precinct":"123",
        "Votes":"1705"
    },
    {
        "Party":"REP",
        "Precinct":"125",
        "Votes":"282"
    },
    {
        "Party":"DEM",
        "Precinct":"125",
        "Votes":"849"
    },
    {
        "Party":"REP",
        "Precinct":"126",
        "Votes":"82"
    },
    {
        "Party":"DEM",
        "Precinct":"126",
        "Votes":"461"
    },
    {
        "Party":"REP",
        "Precinct":"127",
        "Votes":"286"
    },
    {
        "Party":"DEM",
        "Precinct":"127",
        "Votes":"1054"
    },
    {
        "Party":"REP",
        "Precinct":"128",
        "Votes":"527"
    },
    {
        "Party":"DEM",
        "Precinct":"128",
        "Votes":"1168"
    },
    {
        "Party":"REP",
        "Precinct":"129",
        "Votes":"566"
    },
    {
        "Party":"DEM",
        "Precinct":"129",
        "Votes":"1243"
    },
    {
        "Party":"REP",
        "Precinct":"130",
        "Votes":"878"
    },
    {
        "Party":"DEM",
        "Precinct":"130",
        "Votes":"1512"
    },
    {
        "Party":"REP",
        "Precinct":"131",
        "Votes":"391"
    },
    {
        "Party":"DEM",
        "Precinct":"131",
        "Votes":"511"
    },
    {
        "Party":"REP",
        "Precinct":"132",
        "Votes":"471"
    },
    {
        "Party":"DEM",
        "Precinct":"132",
        "Votes":"526"
    },
    {
        "Party":"REP",
        "Precinct":"133",
        "Votes":"475"
    },
    {
        "Party":"DEM",
        "Precinct":"133",
        "Votes":"610"
    },
    {
        "Party":"REP",
        "Precinct":"134",
        "Votes":"312"
    },
    {
        "Party":"DEM",
        "Precinct":"134",
        "Votes":"811"
    },
    {
        "Party":"REP",
        "Precinct":"135",
        "Votes":"903"
    },
    {
        "Party":"DEM",
        "Precinct":"135",
        "Votes":"1854"
    },
    {
        "Party":"REP",
        "Precinct":"136",
        "Votes":"550"
    },
    {
        "Party":"DEM",
        "Precinct":"136",
        "Votes":"903"
    },
    {
        "Party":"REP",
        "Precinct":"137",
        "Votes":"462"
    },
    {
        "Party":"DEM",
        "Precinct":"137",
        "Votes":"686"
    },
    {
        "Party":"REP",
        "Precinct":"138",
        "Votes":"1213"
    },
    {
        "Party":"DEM",
        "Precinct":"138",
        "Votes":"1061"
    },
    {
        "Party":"REP",
        "Precinct":"139",
        "Votes":"536"
    },
    {
        "Party":"DEM",
        "Precinct":"139",
        "Votes":"609"
    },
    {
        "Party":"REP",
        "Precinct":"140",
        "Votes":"1470"
    },
    {
        "Party":"DEM",
        "Precinct":"140",
        "Votes":"1848"
    },
    {
        "Party":"REP",
        "Precinct":"141",
        "Votes":"616"
    },
    {
        "Party":"DEM",
        "Precinct":"141",
        "Votes":"945"
    },
    {
        "Party":"REP",
        "Precinct":"142",
        "Votes":"941"
    },
    {
        "Party":"DEM",
        "Precinct":"142",
        "Votes":"882"
    },
    {
        "Party":"REP",
        "Precinct":"143",
        "Votes":"1078"
    },
    {
        "Party":"DEM",
        "Precinct":"143",
        "Votes":"686"
    },
    {
        "Party":"REP",
        "Precinct":"144",
        "Votes":"1694"
    },
    {
        "Party":"DEM",
        "Precinct":"144",
        "Votes":"1372"
    },
    {
        "Party":"REP",
        "Precinct":"145",
        "Votes":"741"
    },
    {
        "Party":"DEM",
        "Precinct":"145",
        "Votes":"780"
    },
    {
        "Party":"REP",
        "Precinct":"146",
        "Votes":"416"
    },
    {
        "Party":"DEM",
        "Precinct":"146",
        "Votes":"439"
    },
    {
        "Party":"REP",
        "Precinct":"147",
        "Votes":"367"
    },
    {
        "Party":"DEM",
        "Precinct":"147",
        "Votes":"408"
    },
    {
        "Party":"REP",
        "Precinct":"148",
        "Votes":"1425"
    },
    {
        "Party":"DEM",
        "Precinct":"148",
        "Votes":"1668"
    },
    {
        "Party":"REP",
        "Precinct":"149",
        "Votes":"336"
    },
    {
        "Party":"DEM",
        "Precinct":"149",
        "Votes":"329"
    },
    {
        "Party":"REP",
        "Precinct":"150",
        "Votes":"1359"
    },
    {
        "Party":"DEM",
        "Precinct":"150",
        "Votes":"1365"
    },
    {
        "Party":"REP",
        "Precinct":"151",
        "Votes":"532"
    },
    {
        "Party":"DEM",
        "Precinct":"151",
        "Votes":"543"
    },
    {
        "Party":"REP",
        "Precinct":"152",
        "Votes":"586"
    },
    {
        "Party":"DEM",
        "Precinct":"152",
        "Votes":"672"
    },
    {
        "Party":"REP",
        "Precinct":"153",
        "Votes":"1395"
    },
    {
        "Party":"DEM",
        "Precinct":"153",
        "Votes":"1545"
    },
    {
        "Party":"REP",
        "Precinct":"154",
        "Votes":"537"
    },
    {
        "Party":"DEM",
        "Precinct":"154",
        "Votes":"418"
    },
    {
        "Party":"REP",
        "Precinct":"155",
        "Votes":"1450"
    },
    {
        "Party":"DEM",
        "Precinct":"155",
        "Votes":"1607"
    },
    {
        "Party":"REP",
        "Precinct":"156",
        "Votes":"877"
    },
    {
        "Party":"DEM",
        "Precinct":"156",
        "Votes":"1003"
    },
    {
        "Party":"REP",
        "Precinct":"157",
        "Votes":"316"
    },
    {
        "Party":"DEM",
        "Precinct":"157",
        "Votes":"263"
    },
    {
        "Party":"REP",
        "Precinct":"158",
        "Votes":"579"
    },
    {
        "Party":"DEM",
        "Precinct":"158",
        "Votes":"624"
    },
    {
        "Party":"REP",
        "Precinct":"159",
        "Votes":"1142"
    },
    {
        "Party":"DEM",
        "Precinct":"159",
        "Votes":"1161"
    },
    {
        "Party":"REP",
        "Precinct":"160",
        "Votes":"1229"
    },
    {
        "Party":"DEM",
        "Precinct":"160",
        "Votes":"848"
    },
    {
        "Party":"REP",
        "Precinct":"161",
        "Votes":"1043"
    },
    {
        "Party":"DEM",
        "Precinct":"161",
        "Votes":"1564"
    },
    {
        "Party":"REP",
        "Precinct":"162",
        "Votes":"1260"
    },
    {
        "Party":"DEM",
        "Precinct":"162",
        "Votes":"2244"
    },
    {
        "Party":"REP",
        "Precinct":"163",
        "Votes":"579"
    },
    {
        "Party":"DEM",
        "Precinct":"163",
        "Votes":"443"
    },
    {
        "Party":"REP",
        "Precinct":"164",
        "Votes":"16"
    },
    {
        "Party":"DEM",
        "Precinct":"164",
        "Votes":"14"
    },
    {
        "Party":"REP",
        "Precinct":"165",
        "Votes":"4"
    },
    {
        "Party":"DEM",
        "Precinct":"165",
        "Votes":"7"
    },
    {
        "Party":"REP",
        "Precinct":"200",
        "Votes":"821"
    },
    {
        "Party":"DEM",
        "Precinct":"200",
        "Votes":"570"
    },
    {
        "Party":"REP",
        "Precinct":"201",
        "Votes":"931"
    },
    {
        "Party":"DEM",
        "Precinct":"201",
        "Votes":"1202"
    },
    {
        "Party":"REP",
        "Precinct":"202",
        "Votes":"871"
    },
    {
        "Party":"DEM",
        "Precinct":"202",
        "Votes":"862"
    },
    {
        "Party":"REP",
        "Precinct":"203",
        "Votes":"118"
    },
    {
        "Party":"DEM",
        "Precinct":"203",
        "Votes":"925"
    },
    {
        "Party":"REP",
        "Precinct":"204",
        "Votes":"20"
    },
    {
        "Party":"DEM",
        "Precinct":"204",
        "Votes":"462"
    },
    {
        "Party":"REP",
        "Precinct":"205",
        "Votes":"87"
    },
    {
        "Party":"DEM",
        "Precinct":"205",
        "Votes":"1073"
    },
    {
        "Party":"REP",
        "Precinct":"206",
        "Votes":"206"
    },
    {
        "Party":"DEM",
        "Precinct":"206",
        "Votes":"511"
    },
    {
        "Party":"REP",
        "Precinct":"207",
        "Votes":"227"
    },
    {
        "Party":"DEM",
        "Precinct":"207",
        "Votes":"404"
    },
    {
        "Party":"REP",
        "Precinct":"208",
        "Votes":"1273"
    },
    {
        "Party":"DEM",
        "Precinct":"208",
        "Votes":"1201"
    },
    {
        "Party":"REP",
        "Precinct":"209",
        "Votes":"570"
    },
    {
        "Party":"DEM",
        "Precinct":"209",
        "Votes":"1034"
    },
    {
        "Party":"REP",
        "Precinct":"210",
        "Votes":"588"
    },
    {
        "Party":"DEM",
        "Precinct":"210",
        "Votes":"808"
    },
    {
        "Party":"REP",
        "Precinct":"211",
        "Votes":"281"
    },
    {
        "Party":"DEM",
        "Precinct":"211",
        "Votes":"254"
    },
    {
        "Party":"REP",
        "Precinct":"212",
        "Votes":"334"
    },
    {
        "Party":"DEM",
        "Precinct":"212",
        "Votes":"335"
    },
    {
        "Party":"REP",
        "Precinct":"213",
        "Votes":"409"
    },
    {
        "Party":"DEM",
        "Precinct":"213",
        "Votes":"482"
    },
    {
        "Party":"REP",
        "Precinct":"214",
        "Votes":"1541"
    },
    {
        "Party":"DEM",
        "Precinct":"214",
        "Votes":"1619"
    },
    {
        "Party":"REP",
        "Precinct":"215",
        "Votes":"754"
    },
    {
        "Party":"DEM",
        "Precinct":"215",
        "Votes":"363"
    },
    {
        "Party":"REP",
        "Precinct":"216",
        "Votes":"782"
    },
    {
        "Party":"DEM",
        "Precinct":"216",
        "Votes":"751"
    },
    {
        "Party":"REP",
        "Precinct":"217",
        "Votes":"2"
    },
    {
        "Party":"DEM",
        "Precinct":"217",
        "Votes":"6"
    },
    {
        "Party":"REP",
        "Precinct":"218",
        "Votes":"139"
    },
    {
        "Party":"DEM",
        "Precinct":"218",
        "Votes":"298"
    },
    {
        "Party":"REP",
        "Precinct":"219",
        "Votes":"439"
    },
    {
        "Party":"DEM",
        "Precinct":"219",
        "Votes":"531"
    },
    {
        "Party":"REP",
        "Precinct":"220",
        "Votes":"269"
    },
    {
        "Party":"DEM",
        "Precinct":"220",
        "Votes":"500"
    },
    {
        "Party":"REP",
        "Precinct":"221",
        "Votes":"528"
    },
    {
        "Party":"DEM",
        "Precinct":"221",
        "Votes":"785"
    },
    {
        "Party":"REP",
        "Precinct":"222",
        "Votes":"1311"
    },
    {
        "Party":"DEM",
        "Precinct":"222",
        "Votes":"1435"
    },
    {
        "Party":"REP",
        "Precinct":"223",
        "Votes":"34"
    },
    {
        "Party":"DEM",
        "Precinct":"223",
        "Votes":"49"
    },
    {
        "Party":"REP",
        "Precinct":"224",
        "Votes":"38"
    },
    {
        "Party":"DEM",
        "Precinct":"224",
        "Votes":"1048"
    },
    {
        "Party":"REP",
        "Precinct":"225",
        "Votes":"381"
    },
    {
        "Party":"DEM",
        "Precinct":"225",
        "Votes":"834"
    },
    {
        "Party":"REP",
        "Precinct":"226",
        "Votes":"40"
    },
    {
        "Party":"DEM",
        "Precinct":"226",
        "Votes":"549"
    },
    {
        "Party":"REP",
        "Precinct":"227",
        "Votes":"198"
    },
    {
        "Party":"DEM",
        "Precinct":"227",
        "Votes":"1196"
    },
    {
        "Party":"REP",
        "Precinct":"228",
        "Votes":"174"
    },
    {
        "Party":"DEM",
        "Precinct":"228",
        "Votes":"507"
    },
    {
        "Party":"REP",
        "Precinct":"229",
        "Votes":"725"
    },
    {
        "Party":"DEM",
        "Precinct":"229",
        "Votes":"810"
    },
    {
        "Party":"REP",
        "Precinct":"230",
        "Votes":"675"
    },
    {
        "Party":"DEM",
        "Precinct":"230",
        "Votes":"576"
    },
    {
        "Party":"REP",
        "Precinct":"231",
        "Votes":"1111"
    },
    {
        "Party":"DEM",
        "Precinct":"231",
        "Votes":"1062"
    },
    {
        "Party":"REP",
        "Precinct":"232",
        "Votes":"894"
    },
    {
        "Party":"DEM",
        "Precinct":"232",
        "Votes":"776"
    },
    {
        "Party":"REP",
        "Precinct":"233",
        "Votes":"509"
    },
    {
        "Party":"DEM",
        "Precinct":"233",
        "Votes":"709"
    },
    {
        "Party":"REP",
        "Precinct":"234",
        "Votes":"549"
    },
    {
        "Party":"DEM",
        "Precinct":"234",
        "Votes":"557"
    },
    {
        "Party":"REP",
        "Precinct":"235",
        "Votes":"782"
    },
    {
        "Party":"DEM",
        "Precinct":"235",
        "Votes":"701"
    },
    {
        "Party":"REP",
        "Precinct":"236",
        "Votes":"783"
    },
    {
        "Party":"DEM",
        "Precinct":"236",
        "Votes":"707"
    },
    {
        "Party":"REP",
        "Precinct":"237",
        "Votes":"807"
    },
    {
        "Party":"DEM",
        "Precinct":"237",
        "Votes":"767"
    },
    {
        "Party":"REP",
        "Precinct":"238",
        "Votes":"620"
    },
    {
        "Party":"DEM",
        "Precinct":"238",
        "Votes":"613"
    },
    {
        "Party":"REP",
        "Precinct":"239",
        "Votes":"1003"
    },
    {
        "Party":"DEM",
        "Precinct":"239",
        "Votes":"1214"
    },
    {
        "Party":"REP",
        "Precinct":"240",
        "Votes":"705"
    },
    {
        "Party":"DEM",
        "Precinct":"240",
        "Votes":"570"
    },
    {
        "Party":"REP",
        "Precinct":"241",
        "Votes":"889"
    },
    {
        "Party":"DEM",
        "Precinct":"241",
        "Votes":"771"
    },
    {
        "Party":"REP",
        "Precinct":"242",
        "Votes":"784"
    },
    {
        "Party":"DEM",
        "Precinct":"242",
        "Votes":"805"
    },
    {
        "Party":"REP",
        "Precinct":"243",
        "Votes":"480"
    },
    {
        "Party":"DEM",
        "Precinct":"243",
        "Votes":"496"
    },
    {
        "Party":"REP",
        "Precinct":"244",
        "Votes":"625"
    },
    {
        "Party":"DEM",
        "Precinct":"244",
        "Votes":"539"
    },
    {
        "Party":"REP",
        "Precinct":"245",
        "Votes":"636"
    },
    {
        "Party":"DEM",
        "Precinct":"245",
        "Votes":"471"
    },
    {
        "Party":"REP",
        "Precinct":"246",
        "Votes":"544"
    },
    {
        "Party":"DEM",
        "Precinct":"246",
        "Votes":"473"
    },
    {
        "Party":"REP",
        "Precinct":"247",
        "Votes":"867"
    },
    {
        "Party":"DEM",
        "Precinct":"247",
        "Votes":"750"
    },
    {
        "Party":"REP",
        "Precinct":"248",
        "Votes":"736"
    },
    {
        "Party":"DEM",
        "Precinct":"248",
        "Votes":"667"
    },
    {
        "Party":"REP",
        "Precinct":"249",
        "Votes":"308"
    },
    {
        "Party":"DEM",
        "Precinct":"249",
        "Votes":"266"
    },
    {
        "Party":"REP",
        "Precinct":"250",
        "Votes":"1062"
    },
    {
        "Party":"DEM",
        "Precinct":"250",
        "Votes":"948"
    },
    {
        "Party":"REP",
        "Precinct":"251",
        "Votes":"988"
    },
    {
        "Party":"DEM",
        "Precinct":"251",
        "Votes":"711"
    },
    {
        "Party":"REP",
        "Precinct":"252",
        "Votes":"957"
    },
    {
        "Party":"DEM",
        "Precinct":"252",
        "Votes":"830"
    },
    {
        "Party":"REP",
        "Precinct":"253",
        "Votes":"4"
    },
    {
        "Party":"DEM",
        "Precinct":"253",
        "Votes":"2"
    },
    {
        "Party":"REP",
        "Precinct":"254",
        "Votes":"647"
    },
    {
        "Party":"DEM",
        "Precinct":"254",
        "Votes":"446"
    },
    {
        "Party":"REP",
        "Precinct":"255",
        "Votes":"848"
    },
    {
        "Party":"DEM",
        "Precinct":"255",
        "Votes":"624"
    },
    {
        "Party":"REP",
        "Precinct":"256",
        "Votes":"690"
    },
    {
        "Party":"DEM",
        "Precinct":"256",
        "Votes":"482"
    },
    {
        "Party":"REP",
        "Precinct":"257",
        "Votes":"1144"
    },
    {
        "Party":"DEM",
        "Precinct":"257",
        "Votes":"781"
    },
    {
        "Party":"REP",
        "Precinct":"258",
        "Votes":"402"
    },
    {
        "Party":"DEM",
        "Precinct":"258",
        "Votes":"326"
    },
    {
        "Party":"REP",
        "Precinct":"259",
        "Votes":"2028"
    },
    {
        "Party":"DEM",
        "Precinct":"259",
        "Votes":"1902"
    },
    {
        "Party":"REP",
        "Precinct":"260",
        "Votes":"522"
    },
    {
        "Party":"DEM",
        "Precinct":"260",
        "Votes":"505"
    },
    {
        "Party":"REP",
        "Precinct":"261",
        "Votes":"721"
    },
    {
        "Party":"DEM",
        "Precinct":"261",
        "Votes":"631"
    },
    {
        "Party":"REP",
        "Precinct":"262",
        "Votes":"0"
    },
    {
        "Party":"DEM",
        "Precinct":"262",
        "Votes":"0"
    },
    {
        "Party":"REP",
        "Precinct":"263",
        "Votes":"742"
    },
    {
        "Party":"DEM",
        "Precinct":"263",
        "Votes":"608"
    },
    {
        "Party":"REP",
        "Precinct":"264",
        "Votes":"108"
    },
    {
        "Party":"DEM",
        "Precinct":"264",
        "Votes":"74"
    },
    {
        "Party":"REP",
        "Precinct":"265",
        "Votes":"706"
    },
    {
        "Party":"DEM",
        "Precinct":"265",
        "Votes":"682"
    },
    {
        "Party":"REP",
        "Precinct":"266",
        "Votes":"1420"
    },
    {
        "Party":"DEM",
        "Precinct":"266",
        "Votes":"906"
    },
    {
        "Party":"REP",
        "Precinct":"267",
        "Votes":"225"
    },
    {
        "Party":"DEM",
        "Precinct":"267",
        "Votes":"153"
    },
    {
        "Party":"REP",
        "Precinct":"268",
        "Votes":"674"
    },
    {
        "Party":"DEM",
        "Precinct":"268",
        "Votes":"515"
    },
    {
        "Party":"REP",
        "Precinct":"269",
        "Votes":"712"
    },
    {
        "Party":"DEM",
        "Precinct":"269",
        "Votes":"587"
    },
    {
        "Party":"REP",
        "Precinct":"270",
        "Votes":"128"
    },
    {
        "Party":"DEM",
        "Precinct":"270",
        "Votes":"52"
    },
    {
        "Party":"REP",
        "Precinct":"271",
        "Votes":"25"
    },
    {
        "Party":"DEM",
        "Precinct":"271",
        "Votes":"37"
    },
    {
        "Party":"REP",
        "Precinct":"272",
        "Votes":"453"
    },
    {
        "Party":"DEM",
        "Precinct":"272",
        "Votes":"373"
    },
    {
        "Party":"REP",
        "Precinct":"273",
        "Votes":"258"
    },
    {
        "Party":"DEM",
        "Precinct":"273",
        "Votes":"201"
    },
    {
        "Party":"REP",
        "Precinct":"274",
        "Votes":"761"
    },
    {
        "Party":"DEM",
        "Precinct":"274",
        "Votes":"625"
    },
    {
        "Party":"REP",
        "Precinct":"275",
        "Votes":"311"
    },
    {
        "Party":"DEM",
        "Precinct":"275",
        "Votes":"258"
    },
    {
        "Party":"REP",
        "Precinct":"301",
        "Votes":"582"
    },
    {
        "Party":"DEM",
        "Precinct":"301",
        "Votes":"385"
    },
    {
        "Party":"REP",
        "Precinct":"302",
        "Votes":"936"
    },
    {
        "Party":"DEM",
        "Precinct":"302",
        "Votes":"808"
    },
    {
        "Party":"REP",
        "Precinct":"303",
        "Votes":"834"
    },
    {
        "Party":"DEM",
        "Precinct":"303",
        "Votes":"540"
    },
    {
        "Party":"REP",
        "Precinct":"304",
        "Votes":"492"
    },
    {
        "Party":"DEM",
        "Precinct":"304",
        "Votes":"323"
    },
    {
        "Party":"REP",
        "Precinct":"305",
        "Votes":"1238"
    },
    {
        "Party":"DEM",
        "Precinct":"305",
        "Votes":"847"
    },
    {
        "Party":"REP",
        "Precinct":"306",
        "Votes":"1264"
    },
    {
        "Party":"DEM",
        "Precinct":"306",
        "Votes":"832"
    },
    {
        "Party":"REP",
        "Precinct":"307",
        "Votes":"1548"
    },
    {
        "Party":"DEM",
        "Precinct":"307",
        "Votes":"1080"
    },
    {
        "Party":"REP",
        "Precinct":"308",
        "Votes":"578"
    },
    {
        "Party":"DEM",
        "Precinct":"308",
        "Votes":"310"
    },
    {
        "Party":"REP",
        "Precinct":"309",
        "Votes":"2286"
    },
    {
        "Party":"DEM",
        "Precinct":"309",
        "Votes":"1429"
    },
    {
        "Party":"REP",
        "Precinct":"310",
        "Votes":"1314"
    },
    {
        "Party":"DEM",
        "Precinct":"310",
        "Votes":"927"
    },
    {
        "Party":"REP",
        "Precinct":"311",
        "Votes":"725"
    },
    {
        "Party":"DEM",
        "Precinct":"311",
        "Votes":"454"
    },
    {
        "Party":"REP",
        "Precinct":"312",
        "Votes":"703"
    },
    {
        "Party":"DEM",
        "Precinct":"312",
        "Votes":"466"
    },
    {
        "Party":"REP",
        "Precinct":"313",
        "Votes":"967"
    },
    {
        "Party":"DEM",
        "Precinct":"313",
        "Votes":"498"
    },
    {
        "Party":"REP",
        "Precinct":"314",
        "Votes":"704"
    },
    {
        "Party":"DEM",
        "Precinct":"314",
        "Votes":"387"
    },
    {
        "Party":"REP",
        "Precinct":"315",
        "Votes":"589"
    },
    {
        "Party":"DEM",
        "Precinct":"315",
        "Votes":"357"
    },
    {
        "Party":"REP",
        "Precinct":"316",
        "Votes":"338"
    },
    {
        "Party":"DEM",
        "Precinct":"316",
        "Votes":"184"
    },
    {
        "Party":"REP",
        "Precinct":"317",
        "Votes":"1211"
    },
    {
        "Party":"DEM",
        "Precinct":"317",
        "Votes":"921"
    },
    {
        "Party":"REP",
        "Precinct":"318",
        "Votes":"595"
    },
    {
        "Party":"DEM",
        "Precinct":"318",
        "Votes":"423"
    },
    {
        "Party":"REP",
        "Precinct":"319",
        "Votes":"196"
    },
    {
        "Party":"DEM",
        "Precinct":"319",
        "Votes":"81"
    },
    {
        "Party":"REP",
        "Precinct":"320",
        "Votes":"1057"
    },
    {
        "Party":"DEM",
        "Precinct":"320",
        "Votes":"823"
    },
    {
        "Party":"REP",
        "Precinct":"321",
        "Votes":"520"
    },
    {
        "Party":"DEM",
        "Precinct":"321",
        "Votes":"393"
    },
    {
        "Party":"REP",
        "Precinct":"322",
        "Votes":"1971"
    },
    {
        "Party":"DEM",
        "Precinct":"322",
        "Votes":"1732"
    },
    {
        "Party":"REP",
        "Precinct":"323",
        "Votes":"757"
    },
    {
        "Party":"DEM",
        "Precinct":"323",
        "Votes":"702"
    },
    {
        "Party":"REP",
        "Precinct":"324",
        "Votes":"241"
    },
    {
        "Party":"DEM",
        "Precinct":"324",
        "Votes":"743"
    },
    {
        "Party":"REP",
        "Precinct":"325",
        "Votes":"945"
    },
    {
        "Party":"DEM",
        "Precinct":"325",
        "Votes":"831"
    },
    {
        "Party":"REP",
        "Precinct":"326",
        "Votes":"649"
    },
    {
        "Party":"DEM",
        "Precinct":"326",
        "Votes":"609"
    },
    {
        "Party":"REP",
        "Precinct":"327",
        "Votes":"1362"
    },
    {
        "Party":"DEM",
        "Precinct":"327",
        "Votes":"1082"
    },
    {
        "Party":"REP",
        "Precinct":"328",
        "Votes":"720"
    },
    {
        "Party":"DEM",
        "Precinct":"328",
        "Votes":"623"
    },
    {
        "Party":"REP",
        "Precinct":"329",
        "Votes":"689"
    },
    {
        "Party":"DEM",
        "Precinct":"329",
        "Votes":"579"
    },
    {
        "Party":"REP",
        "Precinct":"330",
        "Votes":"481"
    },
    {
        "Party":"DEM",
        "Precinct":"330",
        "Votes":"514"
    },
    {
        "Party":"REP",
        "Precinct":"331",
        "Votes":"908"
    },
    {
        "Party":"DEM",
        "Precinct":"331",
        "Votes":"1212"
    },
    {
        "Party":"REP",
        "Precinct":"332",
        "Votes":"0"
    },
    {
        "Party":"DEM",
        "Precinct":"332",
        "Votes":"0"
    },
    {
        "Party":"REP",
        "Precinct":"333",
        "Votes":"695"
    },
    {
        "Party":"DEM",
        "Precinct":"333",
        "Votes":"571"
    },
    {
        "Party":"REP",
        "Precinct":"334",
        "Votes":"749"
    },
    {
        "Party":"DEM",
        "Precinct":"334",
        "Votes":"728"
    },
    {
        "Party":"REP",
        "Precinct":"335",
        "Votes":"998"
    },
    {
        "Party":"DEM",
        "Precinct":"335",
        "Votes":"799"
    },
    {
        "Party":"REP",
        "Precinct":"336",
        "Votes":"792"
    },
    {
        "Party":"DEM",
        "Precinct":"336",
        "Votes":"725"
    },
    {
        "Party":"REP",
        "Precinct":"337",
        "Votes":"1337"
    },
    {
        "Party":"DEM",
        "Precinct":"337",
        "Votes":"1127"
    },
    {
        "Party":"REP",
        "Precinct":"338",
        "Votes":"937"
    },
    {
        "Party":"DEM",
        "Precinct":"338",
        "Votes":"681"
    },
    {
        "Party":"REP",
        "Precinct":"339",
        "Votes":"841"
    },
    {
        "Party":"DEM",
        "Precinct":"339",
        "Votes":"760"
    },
    {
        "Party":"REP",
        "Precinct":"340",
        "Votes":"716"
    },
    {
        "Party":"DEM",
        "Precinct":"340",
        "Votes":"555"
    },
    {
        "Party":"REP",
        "Precinct":"341",
        "Votes":"747"
    },
    {
        "Party":"DEM",
        "Precinct":"341",
        "Votes":"612"
    },
    {
        "Party":"REP",
        "Precinct":"342",
        "Votes":"818"
    },
    {
        "Party":"DEM",
        "Precinct":"342",
        "Votes":"617"
    },
    {
        "Party":"REP",
        "Precinct":"343",
        "Votes":"1191"
    },
    {
        "Party":"DEM",
        "Precinct":"343",
        "Votes":"634"
    },
    {
        "Party":"REP",
        "Precinct":"344",
        "Votes":"1899"
    },
    {
        "Party":"DEM",
        "Precinct":"344",
        "Votes":"948"
    },
    {
        "Party":"REP",
        "Precinct":"345",
        "Votes":"1170"
    },
    {
        "Party":"DEM",
        "Precinct":"345",
        "Votes":"1154"
    },
    {
        "Party":"REP",
        "Precinct":"346",
        "Votes":"682"
    },
    {
        "Party":"DEM",
        "Precinct":"346",
        "Votes":"760"
    },
    {
        "Party":"REP",
        "Precinct":"347",
        "Votes":"1094"
    },
    {
        "Party":"DEM",
        "Precinct":"347",
        "Votes":"715"
    },
    {
        "Party":"REP",
        "Precinct":"348",
        "Votes":"1120"
    },
    {
        "Party":"DEM",
        "Precinct":"348",
        "Votes":"687"
    },
    {
        "Party":"REP",
        "Precinct":"349",
        "Votes":"1275"
    },
    {
        "Party":"DEM",
        "Precinct":"349",
        "Votes":"821"
    },
    {
        "Party":"REP",
        "Precinct":"350",
        "Votes":"695"
    },
    {
        "Party":"DEM",
        "Precinct":"350",
        "Votes":"522"
    },
    {
        "Party":"REP",
        "Precinct":"401",
        "Votes":"1766"
    },
    {
        "Party":"DEM",
        "Precinct":"401",
        "Votes":"1019"
    },
    {
        "Party":"REP",
        "Precinct":"402",
        "Votes":"787"
    },
    {
        "Party":"DEM",
        "Precinct":"402",
        "Votes":"582"
    },
    {
        "Party":"REP",
        "Precinct":"403",
        "Votes":"925"
    },
    {
        "Party":"DEM",
        "Precinct":"403",
        "Votes":"681"
    },
    {
        "Party":"REP",
        "Precinct":"404",
        "Votes":"809"
    },
    {
        "Party":"DEM",
        "Precinct":"404",
        "Votes":"616"
    },
    {
        "Party":"REP",
        "Precinct":"405",
        "Votes":"914"
    },
    {
        "Party":"DEM",
        "Precinct":"405",
        "Votes":"646"
    },
    {
        "Party":"REP",
        "Precinct":"406",
        "Votes":"888"
    },
    {
        "Party":"DEM",
        "Precinct":"406",
        "Votes":"489"
    },
    {
        "Party":"REP",
        "Precinct":"407",
        "Votes":"614"
    },
    {
        "Party":"DEM",
        "Precinct":"407",
        "Votes":"368"
    },
    {
        "Party":"REP",
        "Precinct":"408",
        "Votes":"740"
    },
    {
        "Party":"DEM",
        "Precinct":"408",
        "Votes":"451"
    },
    {
        "Party":"REP",
        "Precinct":"409",
        "Votes":"471"
    },
    {
        "Party":"DEM",
        "Precinct":"409",
        "Votes":"405"
    },
    {
        "Party":"REP",
        "Precinct":"415",
        "Votes":"1518"
    },
    {
        "Party":"DEM",
        "Precinct":"415",
        "Votes":"895"
    },
    {
        "Party":"REP",
        "Precinct":"416",
        "Votes":"555"
    },
    {
        "Party":"DEM",
        "Precinct":"416",
        "Votes":"399"
    },
    {
        "Party":"REP",
        "Precinct":"417",
        "Votes":"611"
    },
    {
        "Party":"DEM",
        "Precinct":"417",
        "Votes":"381"
    },
    {
        "Party":"REP",
        "Precinct":"418",
        "Votes":"908"
    },
    {
        "Party":"DEM",
        "Precinct":"418",
        "Votes":"555"
    },
    {
        "Party":"REP",
        "Precinct":"419",
        "Votes":"596"
    },
    {
        "Party":"DEM",
        "Precinct":"419",
        "Votes":"331"
    },
    {
        "Party":"REP",
        "Precinct":"420",
        "Votes":"1590"
    },
    {
        "Party":"DEM",
        "Precinct":"420",
        "Votes":"1064"
    },
    {
        "Party":"REP",
        "Precinct":"421",
        "Votes":"58"
    },
    {
        "Party":"DEM",
        "Precinct":"421",
        "Votes":"15"
    },
    {
        "Party":"REP",
        "Precinct":"422",
        "Votes":"772"
    },
    {
        "Party":"DEM",
        "Precinct":"422",
        "Votes":"360"
    },
    {
        "Party":"REP",
        "Precinct":"500",
        "Votes":"209"
    },
    {
        "Party":"DEM",
        "Precinct":"500",
        "Votes":"631"
    },
    {
        "Party":"REP",
        "Precinct":"501",
        "Votes":"920"
    },
    {
        "Party":"DEM",
        "Precinct":"501",
        "Votes":"1006"
    },
    {
        "Party":"REP",
        "Precinct":"502",
        "Votes":"775"
    },
    {
        "Party":"DEM",
        "Precinct":"502",
        "Votes":"734"
    },
    {
        "Party":"REP",
        "Precinct":"503",
        "Votes":"666"
    },
    {
        "Party":"DEM",
        "Precinct":"503",
        "Votes":"565"
    },
    {
        "Party":"REP",
        "Precinct":"504",
        "Votes":"1111"
    },
    {
        "Party":"DEM",
        "Precinct":"504",
        "Votes":"891"
    },
    {
        "Party":"REP",
        "Precinct":"505",
        "Votes":"776"
    },
    {
        "Party":"DEM",
        "Precinct":"505",
        "Votes":"790"
    },
    {
        "Party":"REP",
        "Precinct":"506",
        "Votes":"819"
    },
    {
        "Party":"DEM",
        "Precinct":"506",
        "Votes":"778"
    },
    {
        "Party":"REP",
        "Precinct":"507",
        "Votes":"870"
    },
    {
        "Party":"DEM",
        "Precinct":"507",
        "Votes":"646"
    },
    {
        "Party":"REP",
        "Precinct":"508",
        "Votes":"654"
    },
    {
        "Party":"DEM",
        "Precinct":"508",
        "Votes":"569"
    },
    {
        "Party":"REP",
        "Precinct":"509",
        "Votes":"355"
    },
    {
        "Party":"DEM",
        "Precinct":"509",
        "Votes":"438"
    },
    {
        "Party":"REP",
        "Precinct":"510",
        "Votes":"560"
    },
    {
        "Party":"DEM",
        "Precinct":"510",
        "Votes":"681"
    },
    {
        "Party":"REP",
        "Precinct":"511",
        "Votes":"1011"
    },
    {
        "Party":"DEM",
        "Precinct":"511",
        "Votes":"1010"
    },
    {
        "Party":"REP",
        "Precinct":"512",
        "Votes":"286"
    },
    {
        "Party":"DEM",
        "Precinct":"512",
        "Votes":"260"
    },
    {
        "Party":"REP",
        "Precinct":"513",
        "Votes":"1288"
    },
    {
        "Party":"DEM",
        "Precinct":"513",
        "Votes":"705"
    },
    {
        "Party":"REP",
        "Precinct":"514",
        "Votes":"1178"
    },
    {
        "Party":"DEM",
        "Precinct":"514",
        "Votes":"570"
    },
    {
        "Party":"REP",
        "Precinct":"515",
        "Votes":"1436"
    },
    {
        "Party":"DEM",
        "Precinct":"515",
        "Votes":"609"
    },
    {
        "Party":"REP",
        "Precinct":"516",
        "Votes":"654"
    },
    {
        "Party":"DEM",
        "Precinct":"516",
        "Votes":"1540"
    },
    {
        "Party":"REP",
        "Precinct":"517",
        "Votes":"498"
    },
    {
        "Party":"DEM",
        "Precinct":"517",
        "Votes":"955"
    },
    {
        "Party":"REP",
        "Precinct":"518",
        "Votes":"1735"
    },
    {
        "Party":"DEM",
        "Precinct":"518",
        "Votes":"1619"
    },
    {
        "Party":"REP",
        "Precinct":"519",
        "Votes":"1210"
    },
    {
        "Party":"DEM",
        "Precinct":"519",
        "Votes":"782"
    },
    {
        "Party":"REP",
        "Precinct":"520",
        "Votes":"429"
    },
    {
        "Party":"DEM",
        "Precinct":"520",
        "Votes":"350"
    },
    {
        "Party":"REP",
        "Precinct":"521",
        "Votes":"813"
    },
    {
        "Party":"DEM",
        "Precinct":"521",
        "Votes":"683"
    },
    {
        "Party":"REP",
        "Precinct":"522",
        "Votes":"1641"
    },
    {
        "Party":"DEM",
        "Precinct":"522",
        "Votes":"1381"
    },
    {
        "Party":"REP",
        "Precinct":"523",
        "Votes":"877"
    },
    {
        "Party":"DEM",
        "Precinct":"523",
        "Votes":"691"
    },
    {
        "Party":"REP",
        "Precinct":"524",
        "Votes":"394"
    },
    {
        "Party":"DEM",
        "Precinct":"524",
        "Votes":"404"
    },
    {
        "Party":"REP",
        "Precinct":"525",
        "Votes":"461"
    },
    {
        "Party":"DEM",
        "Precinct":"525",
        "Votes":"327"
    },
    {
        "Party":"REP",
        "Precinct":"526",
        "Votes":"2060"
    },
    {
        "Party":"DEM",
        "Precinct":"526",
        "Votes":"1826"
    },
    {
        "Party":"REP",
        "Precinct":"527",
        "Votes":"995"
    },
    {
        "Party":"DEM",
        "Precinct":"527",
        "Votes":"971"
    },
    {
        "Party":"REP",
        "Precinct":"528",
        "Votes":"594"
    },
    {
        "Party":"DEM",
        "Precinct":"528",
        "Votes":"721"
    },
    {
        "Party":"REP",
        "Precinct":"529",
        "Votes":"766"
    },
    {
        "Party":"DEM",
        "Precinct":"529",
        "Votes":"817"
    },
    {
        "Party":"REP",
        "Precinct":"530",
        "Votes":"1186"
    },
    {
        "Party":"DEM",
        "Precinct":"530",
        "Votes":"957"
    },
    {
        "Party":"REP",
        "Precinct":"531",
        "Votes":"1149"
    },
    {
        "Party":"DEM",
        "Precinct":"531",
        "Votes":"842"
    },
    {
        "Party":"REP",
        "Precinct":"532",
        "Votes":"925"
    },
    {
        "Party":"DEM",
        "Precinct":"532",
        "Votes":"629"
    },
    {
        "Party":"REP",
        "Precinct":"533",
        "Votes":"837"
    },
    {
        "Party":"DEM",
        "Precinct":"533",
        "Votes":"670"
    },
    {
        "Party":"REP",
        "Precinct":"534",
        "Votes":"1062"
    },
    {
        "Party":"DEM",
        "Precinct":"534",
        "Votes":"807"
    },
    {
        "Party":"REP",
        "Precinct":"535",
        "Votes":"1382"
    },
    {
        "Party":"DEM",
        "Precinct":"535",
        "Votes":"1385"
    },
    {
        "Party":"REP",
        "Precinct":"536",
        "Votes":"1245"
    },
    {
        "Party":"DEM",
        "Precinct":"536",
        "Votes":"827"
    },
    {
        "Party":"REP",
        "Precinct":"537",
        "Votes":"1199"
    },
    {
        "Party":"DEM",
        "Precinct":"537",
        "Votes":"1490"
    },
    {
        "Party":"REP",
        "Precinct":"538",
        "Votes":"2328"
    },
    {
        "Party":"DEM",
        "Precinct":"538",
        "Votes":"1681"
    },
    {
        "Party":"REP",
        "Precinct":"539",
        "Votes":"1299"
    },
    {
        "Party":"DEM",
        "Precinct":"539",
        "Votes":"900"
    },
    {
        "Party":"REP",
        "Precinct":"540",
        "Votes":"2311"
    },
    {
        "Party":"DEM",
        "Precinct":"540",
        "Votes":"1644"
    },
    {
        "Party":"REP",
        "Precinct":"541",
        "Votes":"1006"
    },
    {
        "Party":"DEM",
        "Precinct":"541",
        "Votes":"683"
    },
    {
        "Party":"REP",
        "Precinct":"542",
        "Votes":"2125"
    },
    {
        "Party":"DEM",
        "Precinct":"542",
        "Votes":"1326"
    },
    {
        "Party":"REP",
        "Precinct":"543",
        "Votes":"1025"
    },
    {
        "Party":"DEM",
        "Precinct":"543",
        "Votes":"651"
    },
    {
        "Party":"REP",
        "Precinct":"544",
        "Votes":"1490"
    },
    {
        "Party":"DEM",
        "Precinct":"544",
        "Votes":"956"
    },
    {
        "Party":"REP",
        "Precinct":"545",
        "Votes":"672"
    },
    {
        "Party":"DEM",
        "Precinct":"545",
        "Votes":"392"
    },
    {
        "Party":"REP",
        "Precinct":"600",
        "Votes":"4"
    },
    {
        "Party":"DEM",
        "Precinct":"600",
        "Votes":"0"
    },
    {
        "Party":"REP",
        "Precinct":"601",
        "Votes":"1527"
    },
    {
        "Party":"DEM",
        "Precinct":"601",
        "Votes":"1615"
    },
    {
        "Party":"REP",
        "Precinct":"602",
        "Votes":"1162"
    },
    {
        "Party":"DEM",
        "Precinct":"602",
        "Votes":"951"
    },
    {
        "Party":"REP",
        "Precinct":"603",
        "Votes":"1021"
    },
    {
        "Party":"DEM",
        "Precinct":"603",
        "Votes":"894"
    },
    {
        "Party":"REP",
        "Precinct":"604",
        "Votes":"351"
    },
    {
        "Party":"DEM",
        "Precinct":"604",
        "Votes":"260"
    },
    {
        "Party":"REP",
        "Precinct":"605",
        "Votes":"454"
    },
    {
        "Party":"DEM",
        "Precinct":"605",
        "Votes":"766"
    },
    {
        "Party":"REP",
        "Precinct":"606",
        "Votes":"905"
    },
    {
        "Party":"DEM",
        "Precinct":"606",
        "Votes":"870"
    },
    {
        "Party":"REP",
        "Precinct":"607",
        "Votes":"720"
    },
    {
        "Party":"DEM",
        "Precinct":"607",
        "Votes":"782"
    },
    {
        "Party":"REP",
        "Precinct":"608",
        "Votes":"779"
    },
    {
        "Party":"DEM",
        "Precinct":"608",
        "Votes":"731"
    },
    {
        "Party":"REP",
        "Precinct":"609",
        "Votes":"662"
    },
    {
        "Party":"DEM",
        "Precinct":"609",
        "Votes":"672"
    },
    {
        "Party":"REP",
        "Precinct":"610",
        "Votes":"707"
    },
    {
        "Party":"DEM",
        "Precinct":"610",
        "Votes":"479"
    },
    {
        "Party":"REP",
        "Precinct":"611",
        "Votes":"1075"
    },
    {
        "Party":"DEM",
        "Precinct":"611",
        "Votes":"851"
    },
    {
        "Party":"REP",
        "Precinct":"612",
        "Votes":"773"
    },
    {
        "Party":"DEM",
        "Precinct":"612",
        "Votes":"852"
    },
    {
        "Party":"REP",
        "Precinct":"613",
        "Votes":"533"
    },
    {
        "Party":"DEM",
        "Precinct":"613",
        "Votes":"550"
    },
    {
        "Party":"REP",
        "Precinct":"614",
        "Votes":"1441"
    },
    {
        "Party":"DEM",
        "Precinct":"614",
        "Votes":"1255"
    },
    {
        "Party":"REP",
        "Precinct":"615",
        "Votes":"1128"
    },
    {
        "Party":"DEM",
        "Precinct":"615",
        "Votes":"977"
    },
    {
        "Party":"REP",
        "Precinct":"616",
        "Votes":"1234"
    },
    {
        "Party":"DEM",
        "Precinct":"616",
        "Votes":"1107"
    },
    {
        "Party":"REP",
        "Precinct":"617",
        "Votes":"1560"
    },
    {
        "Party":"DEM",
        "Precinct":"617",
        "Votes":"1312"
    },
    {
        "Party":"REP",
        "Precinct":"618",
        "Votes":"702"
    },
    {
        "Party":"DEM",
        "Precinct":"618",
        "Votes":"430"
    },
    {
        "Party":"REP",
        "Precinct":"619",
        "Votes":"792"
    },
    {
        "Party":"DEM",
        "Precinct":"619",
        "Votes":"523"
    },
    {
        "Party":"REP",
        "Precinct":"620",
        "Votes":"1210"
    },
    {
        "Party":"DEM",
        "Precinct":"620",
        "Votes":"843"
    },
    {
        "Party":"REP",
        "Precinct":"621",
        "Votes":"1094"
    },
    {
        "Party":"DEM",
        "Precinct":"621",
        "Votes":"968"
    },
    {
        "Party":"REP",
        "Precinct":"622",
        "Votes":"1590"
    },
    {
        "Party":"DEM",
        "Precinct":"622",
        "Votes":"1351"
    },
    {
        "Party":"REP",
        "Precinct":"623",
        "Votes":"1416"
    },
    {
        "Party":"DEM",
        "Precinct":"623",
        "Votes":"1032"
    },
    {
        "Party":"REP",
        "Precinct":"624",
        "Votes":"648"
    },
    {
        "Party":"DEM",
        "Precinct":"624",
        "Votes":"446"
    },
    {
        "Party":"REP",
        "Precinct":"625",
        "Votes":"879"
    },
    {
        "Party":"DEM",
        "Precinct":"625",
        "Votes":"770"
    },
    {
        "Party":"REP",
        "Precinct":"626",
        "Votes":"816"
    },
    {
        "Party":"DEM",
        "Precinct":"626",
        "Votes":"750"
    },
    {
        "Party":"REP",
        "Precinct":"627",
        "Votes":"2809"
    },
    {
        "Party":"DEM",
        "Precinct":"627",
        "Votes":"1863"
    },
    {
        "Party":"REP",
        "Precinct":"628",
        "Votes":"723"
    },
    {
        "Party":"DEM",
        "Precinct":"628",
        "Votes":"571"
    },
    {
        "Party":"REP",
        "Precinct":"629",
        "Votes":"757"
    },
    {
        "Party":"DEM",
        "Precinct":"629",
        "Votes":"705"
    },
    {
        "Party":"REP",
        "Precinct":"630",
        "Votes":"756"
    },
    {
        "Party":"DEM",
        "Precinct":"630",
        "Votes":"623"
    },
    {
        "Party":"REP",
        "Precinct":"631",
        "Votes":"870"
    },
    {
        "Party":"DEM",
        "Precinct":"631",
        "Votes":"805"
    },
    {
        "Party":"REP",
        "Precinct":"632",
        "Votes":"1549"
    },
    {
        "Party":"DEM",
        "Precinct":"632",
        "Votes":"1125"
    },
    {
        "Party":"REP",
        "Precinct":"633",
        "Votes":"1809"
    },
    {
        "Party":"DEM",
        "Precinct":"633",
        "Votes":"1140"
    },
    {
        "Party":"REP",
        "Precinct":"634",
        "Votes":"961"
    },
    {
        "Party":"DEM",
        "Precinct":"634",
        "Votes":"456"
    },
    {
        "Party":"REP",
        "Precinct":"635",
        "Votes":"1217"
    },
    {
        "Party":"DEM",
        "Precinct":"635",
        "Votes":"875"
    },
    {
        "Party":"REP",
        "Precinct":"636",
        "Votes":"1256"
    },
    {
        "Party":"DEM",
        "Precinct":"636",
        "Votes":"755"
    },
    {
        "Party":"REP",
        "Precinct":"637",
        "Votes":"2450"
    },
    {
        "Party":"DEM",
        "Precinct":"637",
        "Votes":"1719"
    },
    {
        "Party":"REP",
        "Precinct":"638",
        "Votes":"1736"
    },
    {
        "Party":"DEM",
        "Precinct":"638",
        "Votes":"999"
    },
    {
        "Party":"REP",
        "Precinct":"701",
        "Votes":"1875"
    },
    {
        "Party":"DEM",
        "Precinct":"701",
        "Votes":"1281"
    },
    {
        "Party":"REP",
        "Precinct":"702",
        "Votes":"689"
    },
    {
        "Party":"DEM",
        "Precinct":"702",
        "Votes":"641"
    },
    {
        "Party":"REP",
        "Precinct":"703",
        "Votes":"610"
    },
    {
        "Party":"DEM",
        "Precinct":"703",
        "Votes":"430"
    },
    {
        "Party":"REP",
        "Precinct":"704",
        "Votes":"1144"
    },
    {
        "Party":"DEM",
        "Precinct":"704",
        "Votes":"795"
    },
    {
        "Party":"REP",
        "Precinct":"705",
        "Votes":"1089"
    },
    {
        "Party":"DEM",
        "Precinct":"705",
        "Votes":"761"
    },
    {
        "Party":"REP",
        "Precinct":"706",
        "Votes":"1103"
    },
    {
        "Party":"DEM",
        "Precinct":"706",
        "Votes":"674"
    },
    {
        "Party":"REP",
        "Precinct":"710",
        "Votes":"302"
    },
    {
        "Party":"DEM",
        "Precinct":"710",
        "Votes":"160"
    },
    {
        "Party":"REP",
        "Precinct":"711",
        "Votes":"1566"
    },
    {
        "Party":"DEM",
        "Precinct":"711",
        "Votes":"766"
    }
]

module.exports=votes;