var votes=[
    {
        "Party":"REP",
        "Precinct":"001",
        "Votes":"1270"
    },
    {
        "Party":"REP",
        "Precinct":"002",
        "Votes":"441"
    },
    {
        "Party":"REP",
        "Precinct":"003",
        "Votes":"1442"
    },
    {
        "Party":"REP",
        "Precinct":"004",
        "Votes":"610"
    },
    {
        "Party":"REP",
        "Precinct":"005",
        "Votes":"1222"
    },
    {
        "Party":"REP",
        "Precinct":"006",
        "Votes":"3718"
    },
    {
        "Party":"REP",
        "Precinct":"007",
        "Votes":"1996"
    },
    {
        "Party":"REP",
        "Precinct":"008",
        "Votes":"2426"
    },
    {
        "Party":"REP",
        "Precinct":"009",
        "Votes":"399"
    },
    {
        "Party":"REP",
        "Precinct":"010",
        "Votes":"503"
    },
    {
        "Party":"REP",
        "Precinct":"011",
        "Votes":"1502"
    },
    {
        "Party":"REP",
        "Precinct":"012",
        "Votes":"880"
    },
    {
        "Party":"REP",
        "Precinct":"013",
        "Votes":"1665"
    },
    {
        "Party":"REP",
        "Precinct":"014",
        "Votes":"2159"
    },
    {
        "Party":"REP",
        "Precinct":"015",
        "Votes":"1288"
    },
    {
        "Party":"REP",
        "Precinct":"016",
        "Votes":"454"
    },
    {
        "Party":"REP",
        "Precinct":"017",
        "Votes":"352"
    },
    {
        "Party":"REP",
        "Precinct":"018",
        "Votes":"508"
    },
    {
        "Party":"REP",
        "Precinct":"019",
        "Votes":"1902"
    },
    {
        "Party":"REP",
        "Precinct":"020",
        "Votes":"248"
    },
    {
        "Party":"REP",
        "Precinct":"021",
        "Votes":"388"
    },
    {
        "Party":"REP",
        "Precinct":"022",
        "Votes":"559"
    },
    {
        "Party":"REP",
        "Precinct":"023",
        "Votes":"873"
    },
    {
        "Party":"REP",
        "Precinct":"024",
        "Votes":"162"
    },
    {
        "Party":"REP",
        "Precinct":"025",
        "Votes":"1305"
    },
    {
        "Party":"REP",
        "Precinct":"026",
        "Votes":"1200"
    },
    {
        "Party":"REP",
        "Precinct":"027",
        "Votes":"3130"
    },
    {
        "Party":"REP",
        "Precinct":"028",
        "Votes":"1484"
    },
    {
        "Party":"REP",
        "Precinct":"029",
        "Votes":"539"
    },
    {
        "Party":"REP",
        "Precinct":"030",
        "Votes":"1160"
    },
    {
        "Party":"REP",
        "Precinct":"031",
        "Votes":"1246"
    },
    {
        "Party":"REP",
        "Precinct":"032",
        "Votes":"1214"
    },
    {
        "Party":"REP",
        "Precinct":"033",
        "Votes":"2727"
    },
    {
        "Party":"REP",
        "Precinct":"034",
        "Votes":"1534"
    },
    {
        "Party":"REP",
        "Precinct":"035",
        "Votes":"1220"
    },
    {
        "Party":"REP",
        "Precinct":"036",
        "Votes":"1788"
    },
    {
        "Party":"REP",
        "Precinct":"037",
        "Votes":"1253"
    },
    {
        "Party":"REP",
        "Precinct":"038",
        "Votes":"1241"
    },
    {
        "Party":"REP",
        "Precinct":"039",
        "Votes":"375"
    },
    {
        "Party":"REP",
        "Precinct":"040",
        "Votes":"356"
    },
    {
        "Party":"REP",
        "Precinct":"041",
        "Votes":"968"
    },
    {
        "Party":"REP",
        "Precinct":"042",
        "Votes":"2048"
    },
    {
        "Party":"REP",
        "Precinct":"043",
        "Votes":"276"
    },
    {
        "Party":"REP",
        "Precinct":"044",
        "Votes":"555"
    },
    {
        "Party":"REP",
        "Precinct":"045",
        "Votes":"2553"
    },
    {
        "Party":"REP",
        "Precinct":"046",
        "Votes":"1422"
    },
    {
        "Party":"REP",
        "Precinct":"047",
        "Votes":"488"
    },
    {
        "Party":"REP",
        "Precinct":"048",
        "Votes":"737"
    },
    {
        "Party":"REP",
        "Precinct":"049",
        "Votes":"628"
    },
    {
        "Party":"REP",
        "Precinct":"050",
        "Votes":"1017"
    },
    {
        "Party":"REP",
        "Precinct":"051",
        "Votes":"1078"
    },
    {
        "Party":"REP",
        "Precinct":"052",
        "Votes":"2301"
    },
    {
        "Party":"REP",
        "Precinct":"053",
        "Votes":"820"
    },
    {
        "Party":"REP",
        "Precinct":"054",
        "Votes":"1198"
    },
    {
        "Party":"REP",
        "Precinct":"055",
        "Votes":"1781"
    },
    {
        "Party":"REP",
        "Precinct":"056",
        "Votes":"295"
    },
    {
        "Party":"REP",
        "Precinct":"057",
        "Votes":"852"
    },
    {
        "Party":"REP",
        "Precinct":"058",
        "Votes":"592"
    },
    {
        "Party":"REP",
        "Precinct":"059",
        "Votes":"2577"
    },
    {
        "Party":"REP",
        "Precinct":"060",
        "Votes":"1312"
    },
    {
        "Party":"REP",
        "Precinct":"061",
        "Votes":"549"
    },
    {
        "Party":"REP",
        "Precinct":"062",
        "Votes":"2284"
    },
    {
        "Party":"REP",
        "Precinct":"063",
        "Votes":"594"
    },
    {
        "Party":"REP",
        "Precinct":"064",
        "Votes":"826"
    },
    {
        "Party":"REP",
        "Precinct":"065",
        "Votes":"1485"
    },
    {
        "Party":"REP",
        "Precinct":"066",
        "Votes":"1396"
    },
    {
        "Party":"REP",
        "Precinct":"067",
        "Votes":"1616"
    },
    {
        "Party":"REP",
        "Precinct":"068",
        "Votes":"1144"
    },
    {
        "Party":"REP",
        "Precinct":"069",
        "Votes":"1408"
    },
    {
        "Party":"REP",
        "Precinct":"070",
        "Votes":"3673"
    },
    {
        "Party":"REP",
        "Precinct":"071",
        "Votes":"773"
    },
    {
        "Party":"REP",
        "Precinct":"072",
        "Votes":"1071"
    },
    {
        "Party":"REP",
        "Precinct":"073",
        "Votes":"2438"
    },
    {
        "Party":"REP",
        "Precinct":"074",
        "Votes":"52"
    },
    {
        "Party":"REP",
        "Precinct":"075",
        "Votes":"1422"
    },
    {
        "Party":"REP",
        "Precinct":"076",
        "Votes":"1352"
    },
    {
        "Party":"REP",
        "Precinct":"077",
        "Votes":"1451"
    },
    {
        "Party":"REP",
        "Precinct":"078",
        "Votes":"1332"
    },
    {
        "Party":"REP",
        "Precinct":"079",
        "Votes":"807"
    },
    {
        "Party":"REP",
        "Precinct":"080",
        "Votes":"529"
    },
    {
        "Party":"REP",
        "Precinct":"081",
        "Votes":"773"
    },
    {
        "Party":"REP",
        "Precinct":"082",
        "Votes":"1756"
    },
    {
        "Party":"REP",
        "Precinct":"083",
        "Votes":"4481"
    },
    {
        "Party":"REP",
        "Precinct":"084",
        "Votes":"1013"
    },
    {
        "Party":"REP",
        "Precinct":"085",
        "Votes":"1139"
    },
    {
        "Party":"REP",
        "Precinct":"086",
        "Votes":"1073"
    },
    {
        "Party":"REP",
        "Precinct":"087",
        "Votes":"709"
    },
    {
        "Party":"REP",
        "Precinct":"088",
        "Votes":"365"
    },
    {
        "Party":"REP",
        "Precinct":"089",
        "Votes":"694"
    },
    {
        "Party":"REP",
        "Precinct":"090",
        "Votes":"1329"
    },
    {
        "Party":"REP",
        "Precinct":"091",
        "Votes":"1687"
    },
    {
        "Party":"REP",
        "Precinct":"092",
        "Votes":"1002"
    },
    {
        "Party":"REP",
        "Precinct":"093",
        "Votes":"1219"
    },
    {
        "Party":"REP",
        "Precinct":"094",
        "Votes":"953"
    },
    {
        "Party":"REP",
        "Precinct":"095",
        "Votes":"1445"
    },
    {
        "Party":"REP",
        "Precinct":"096",
        "Votes":"807"
    },
    {
        "Party":"REP",
        "Precinct":"097",
        "Votes":"1807"
    },
    {
        "Party":"REP",
        "Precinct":"098",
        "Votes":"1106"
    },
    {
        "Party":"REP",
        "Precinct":"099",
        "Votes":"949"
    },
    {
        "Party":"REP",
        "Precinct":"100",
        "Votes":"977"
    },
    {
        "Party":"REP",
        "Precinct":"101",
        "Votes":"1139"
    },
    {
        "Party":"REP",
        "Precinct":"102",
        "Votes":"972"
    },
    {
        "Party":"REP",
        "Precinct":"103",
        "Votes":"1852"
    },
    {
        "Party":"REP",
        "Precinct":"104",
        "Votes":"370"
    },
    {
        "Party":"REP",
        "Precinct":"105",
        "Votes":"1593"
    },
    {
        "Party":"REP",
        "Precinct":"106",
        "Votes":"303"
    },
    {
        "Party":"REP",
        "Precinct":"107",
        "Votes":"1336"
    },
    {
        "Party":"REP",
        "Precinct":"108",
        "Votes":"2142"
    },
    {
        "Party":"REP",
        "Precinct":"109",
        "Votes":"2236"
    },
    {
        "Party":"REP",
        "Precinct":"110",
        "Votes":"3578"
    },
    {
        "Party":"REP",
        "Precinct":"111",
        "Votes":"1735"
    },
    {
        "Party":"REP",
        "Precinct":"112",
        "Votes":"964"
    },
    {
        "Party":"DEM",
        "Precinct":"001",
        "Votes":"1344"
    },
    {
        "Party":"DEM",
        "Precinct":"002",
        "Votes":"240"
    },
    {
        "Party":"DEM",
        "Precinct":"003",
        "Votes":"839"
    },
    {
        "Party":"DEM",
        "Precinct":"004",
        "Votes":"302"
    },
    {
        "Party":"DEM",
        "Precinct":"005",
        "Votes":"570"
    },
    {
        "Party":"DEM",
        "Precinct":"006",
        "Votes":"2163"
    },
    {
        "Party":"DEM",
        "Precinct":"007",
        "Votes":"2071"
    },
    {
        "Party":"DEM",
        "Precinct":"008",
        "Votes":"1560"
    },
    {
        "Party":"DEM",
        "Precinct":"009",
        "Votes":"148"
    },
    {
        "Party":"DEM",
        "Precinct":"010",
        "Votes":"218"
    },
    {
        "Party":"DEM",
        "Precinct":"011",
        "Votes":"795"
    },
    {
        "Party":"DEM",
        "Precinct":"012",
        "Votes":"377"
    },
    {
        "Party":"DEM",
        "Precinct":"013",
        "Votes":"752"
    },
    {
        "Party":"DEM",
        "Precinct":"014",
        "Votes":"1274"
    },
    {
        "Party":"DEM",
        "Precinct":"015",
        "Votes":"979"
    },
    {
        "Party":"DEM",
        "Precinct":"016",
        "Votes":"149"
    },
    {
        "Party":"DEM",
        "Precinct":"017",
        "Votes":"226"
    },
    {
        "Party":"DEM",
        "Precinct":"018",
        "Votes":"354"
    },
    {
        "Party":"DEM",
        "Precinct":"019",
        "Votes":"801"
    },
    {
        "Party":"DEM",
        "Precinct":"020",
        "Votes":"107"
    },
    {
        "Party":"DEM",
        "Precinct":"021",
        "Votes":"259"
    },
    {
        "Party":"DEM",
        "Precinct":"022",
        "Votes":"255"
    },
    {
        "Party":"DEM",
        "Precinct":"023",
        "Votes":"393"
    },
    {
        "Party":"DEM",
        "Precinct":"024",
        "Votes":"128"
    },
    {
        "Party":"DEM",
        "Precinct":"025",
        "Votes":"1035"
    },
    {
        "Party":"DEM",
        "Precinct":"026",
        "Votes":"575"
    },
    {
        "Party":"DEM",
        "Precinct":"027",
        "Votes":"1175"
    },
    {
        "Party":"DEM",
        "Precinct":"028",
        "Votes":"1103"
    },
    {
        "Party":"DEM",
        "Precinct":"029",
        "Votes":"370"
    },
    {
        "Party":"DEM",
        "Precinct":"030",
        "Votes":"920"
    },
    {
        "Party":"DEM",
        "Precinct":"031",
        "Votes":"1112"
    },
    {
        "Party":"DEM",
        "Precinct":"032",
        "Votes":"885"
    },
    {
        "Party":"DEM",
        "Precinct":"033",
        "Votes":"1392"
    },
    {
        "Party":"DEM",
        "Precinct":"034",
        "Votes":"891"
    },
    {
        "Party":"DEM",
        "Precinct":"035",
        "Votes":"799"
    },
    {
        "Party":"DEM",
        "Precinct":"036",
        "Votes":"1378"
    },
    {
        "Party":"DEM",
        "Precinct":"037",
        "Votes":"648"
    },
    {
        "Party":"DEM",
        "Precinct":"038",
        "Votes":"1059"
    },
    {
        "Party":"DEM",
        "Precinct":"039",
        "Votes":"162"
    },
    {
        "Party":"DEM",
        "Precinct":"040",
        "Votes":"210"
    },
    {
        "Party":"DEM",
        "Precinct":"041",
        "Votes":"491"
    },
    {
        "Party":"DEM",
        "Precinct":"042",
        "Votes":"1339"
    },
    {
        "Party":"DEM",
        "Precinct":"043",
        "Votes":"227"
    },
    {
        "Party":"DEM",
        "Precinct":"044",
        "Votes":"370"
    },
    {
        "Party":"DEM",
        "Precinct":"045",
        "Votes":"1027"
    },
    {
        "Party":"DEM",
        "Precinct":"046",
        "Votes":"1042"
    },
    {
        "Party":"DEM",
        "Precinct":"047",
        "Votes":"375"
    },
    {
        "Party":"DEM",
        "Precinct":"048",
        "Votes":"502"
    },
    {
        "Party":"DEM",
        "Precinct":"049",
        "Votes":"302"
    },
    {
        "Party":"DEM",
        "Precinct":"050",
        "Votes":"748"
    },
    {
        "Party":"DEM",
        "Precinct":"051",
        "Votes":"790"
    },
    {
        "Party":"DEM",
        "Precinct":"052",
        "Votes":"1413"
    },
    {
        "Party":"DEM",
        "Precinct":"053",
        "Votes":"617"
    },
    {
        "Party":"DEM",
        "Precinct":"054",
        "Votes":"1016"
    },
    {
        "Party":"DEM",
        "Precinct":"055",
        "Votes":"1152"
    },
    {
        "Party":"DEM",
        "Precinct":"056",
        "Votes":"174"
    },
    {
        "Party":"DEM",
        "Precinct":"057",
        "Votes":"543"
    },
    {
        "Party":"DEM",
        "Precinct":"058",
        "Votes":"412"
    },
    {
        "Party":"DEM",
        "Precinct":"059",
        "Votes":"1635"
    },
    {
        "Party":"DEM",
        "Precinct":"060",
        "Votes":"959"
    },
    {
        "Party":"DEM",
        "Precinct":"061",
        "Votes":"347"
    },
    {
        "Party":"DEM",
        "Precinct":"062",
        "Votes":"1179"
    },
    {
        "Party":"DEM",
        "Precinct":"063",
        "Votes":"384"
    },
    {
        "Party":"DEM",
        "Precinct":"064",
        "Votes":"511"
    },
    {
        "Party":"DEM",
        "Precinct":"065",
        "Votes":"1031"
    },
    {
        "Party":"DEM",
        "Precinct":"066",
        "Votes":"1007"
    },
    {
        "Party":"DEM",
        "Precinct":"067",
        "Votes":"805"
    },
    {
        "Party":"DEM",
        "Precinct":"068",
        "Votes":"636"
    },
    {
        "Party":"DEM",
        "Precinct":"069",
        "Votes":"658"
    },
    {
        "Party":"DEM",
        "Precinct":"070",
        "Votes":"2538"
    },
    {
        "Party":"DEM",
        "Precinct":"071",
        "Votes":"307"
    },
    {
        "Party":"DEM",
        "Precinct":"072",
        "Votes":"810"
    },
    {
        "Party":"DEM",
        "Precinct":"073",
        "Votes":"2106"
    },
    {
        "Party":"DEM",
        "Precinct":"074",
        "Votes":"67"
    },
    {
        "Party":"DEM",
        "Precinct":"075",
        "Votes":"911"
    },
    {
        "Party":"DEM",
        "Precinct":"076",
        "Votes":"680"
    },
    {
        "Party":"DEM",
        "Precinct":"077",
        "Votes":"573"
    },
    {
        "Party":"DEM",
        "Precinct":"078",
        "Votes":"803"
    },
    {
        "Party":"DEM",
        "Precinct":"079",
        "Votes":"239"
    },
    {
        "Party":"DEM",
        "Precinct":"080",
        "Votes":"302"
    },
    {
        "Party":"DEM",
        "Precinct":"081",
        "Votes":"314"
    },
    {
        "Party":"DEM",
        "Precinct":"082",
        "Votes":"884"
    },
    {
        "Party":"DEM",
        "Precinct":"083",
        "Votes":"2273"
    },
    {
        "Party":"DEM",
        "Precinct":"084",
        "Votes":"602"
    },
    {
        "Party":"DEM",
        "Precinct":"085",
        "Votes":"1021"
    },
    {
        "Party":"DEM",
        "Precinct":"086",
        "Votes":"528"
    },
    {
        "Party":"DEM",
        "Precinct":"087",
        "Votes":"366"
    },
    {
        "Party":"DEM",
        "Precinct":"088",
        "Votes":"123"
    },
    {
        "Party":"DEM",
        "Precinct":"089",
        "Votes":"302"
    },
    {
        "Party":"DEM",
        "Precinct":"090",
        "Votes":"1488"
    },
    {
        "Party":"DEM",
        "Precinct":"091",
        "Votes":"822"
    },
    {
        "Party":"DEM",
        "Precinct":"092",
        "Votes":"597"
    },
    {
        "Party":"DEM",
        "Precinct":"093",
        "Votes":"775"
    },
    {
        "Party":"DEM",
        "Precinct":"094",
        "Votes":"498"
    },
    {
        "Party":"DEM",
        "Precinct":"095",
        "Votes":"942"
    },
    {
        "Party":"DEM",
        "Precinct":"096",
        "Votes":"920"
    },
    {
        "Party":"DEM",
        "Precinct":"097",
        "Votes":"1084"
    },
    {
        "Party":"DEM",
        "Precinct":"098",
        "Votes":"947"
    },
    {
        "Party":"DEM",
        "Precinct":"099",
        "Votes":"1286"
    },
    {
        "Party":"DEM",
        "Precinct":"100",
        "Votes":"459"
    },
    {
        "Party":"DEM",
        "Precinct":"101",
        "Votes":"1336"
    },
    {
        "Party":"DEM",
        "Precinct":"102",
        "Votes":"670"
    },
    {
        "Party":"DEM",
        "Precinct":"103",
        "Votes":"940"
    },
    {
        "Party":"DEM",
        "Precinct":"104",
        "Votes":"224"
    },
    {
        "Party":"DEM",
        "Precinct":"105",
        "Votes":"933"
    },
    {
        "Party":"DEM",
        "Precinct":"106",
        "Votes":"223"
    },
    {
        "Party":"DEM",
        "Precinct":"107",
        "Votes":"1549"
    },
    {
        "Party":"DEM",
        "Precinct":"108",
        "Votes":"1251"
    },
    {
        "Party":"DEM",
        "Precinct":"109",
        "Votes":"1493"
    },
    {
        "Party":"DEM",
        "Precinct":"110",
        "Votes":"1897"
    },
    {
        "Party":"DEM",
        "Precinct":"111",
        "Votes":"1550"
    },
    {
        "Party":"DEM",
        "Precinct":"112",
        "Votes":"655"
    }
]

module.exports=votes;