var votes=[
    {
        "Party":"REP",
        "Precinct":"1",
        "Votes":"729"
    },
    {
        "Party":"DEM",
        "Precinct":"1",
        "Votes":"268"
    },
    {
        "Party":"REP",
        "Precinct":"2",
        "Votes":"1128"
    },
    {
        "Party":"DEM",
        "Precinct":"2",
        "Votes":"233"
    },
    {
        "Party":"REP",
        "Precinct":"4",
        "Votes":"2018"
    },
    {
        "Party":"DEM",
        "Precinct":"4",
        "Votes":"1392"
    },
    {
        "Party":"REP",
        "Precinct":"6",
        "Votes":"1978"
    },
    {
        "Party":"DEM",
        "Precinct":"6",
        "Votes":"778"
    },
    {
        "Party":"REP",
        "Precinct":"8",
        "Votes":"1736"
    },
    {
        "Party":"DEM",
        "Precinct":"8",
        "Votes":"714"
    },
    {
        "Party":"REP",
        "Precinct":"9",
        "Votes":"1267"
    },
    {
        "Party":"DEM",
        "Precinct":"9",
        "Votes":"401"
    },
    {
        "Party":"REP",
        "Precinct":"10",
        "Votes":"1961"
    },
    {
        "Party":"DEM",
        "Precinct":"10",
        "Votes":"954"
    },
    {
        "Party":"REP",
        "Precinct":"12",
        "Votes":"1299"
    },
    {
        "Party":"DEM",
        "Precinct":"12",
        "Votes":"641"
    },
    {
        "Party":"REP",
        "Precinct":"13",
        "Votes":"691"
    },
    {
        "Party":"DEM",
        "Precinct":"13",
        "Votes":"306"
    },
    {
        "Party":"REP",
        "Precinct":"14",
        "Votes":"3212"
    },
    {
        "Party":"DEM",
        "Precinct":"14",
        "Votes":"1708"
    },
    {
        "Party":"REP",
        "Precinct":"15",
        "Votes":"1835"
    },
    {
        "Party":"DEM",
        "Precinct":"15",
        "Votes":"1166"
    },
    {
        "Party":"REP",
        "Precinct":"17",
        "Votes":"1643"
    },
    {
        "Party":"DEM",
        "Precinct":"17",
        "Votes":"800"
    },
    {
        "Party":"REP",
        "Precinct":"18",
        "Votes":"885"
    },
    {
        "Party":"DEM",
        "Precinct":"18",
        "Votes":"469"
    },
    {
        "Party":"REP",
        "Precinct":"19",
        "Votes":"3102"
    },
    {
        "Party":"DEM",
        "Precinct":"19",
        "Votes":"1526"
    },
    {
        "Party":"REP",
        "Precinct":"21",
        "Votes":"1345"
    },
    {
        "Party":"DEM",
        "Precinct":"21",
        "Votes":"912"
    },
    {
        "Party":"REP",
        "Precinct":"23",
        "Votes":"1675"
    },
    {
        "Party":"DEM",
        "Precinct":"23",
        "Votes":"1090"
    },
    {
        "Party":"REP",
        "Precinct":"24",
        "Votes":"4015"
    },
    {
        "Party":"DEM",
        "Precinct":"24",
        "Votes":"1658"
    },
    {
        "Party":"REP",
        "Precinct":"25",
        "Votes":"1589"
    },
    {
        "Party":"DEM",
        "Precinct":"25",
        "Votes":"996"
    },
    {
        "Party":"REP",
        "Precinct":"27",
        "Votes":"1459"
    },
    {
        "Party":"DEM",
        "Precinct":"27",
        "Votes":"1077"
    },
    {
        "Party":"REP",
        "Precinct":"30",
        "Votes":"1328"
    },
    {
        "Party":"DEM",
        "Precinct":"30",
        "Votes":"461"
    },
    {
        "Party":"REP",
        "Precinct":"31",
        "Votes":"1848"
    },
    {
        "Party":"DEM",
        "Precinct":"31",
        "Votes":"913"
    },
    {
        "Party":"REP",
        "Precinct":"33",
        "Votes":"754"
    },
    {
        "Party":"DEM",
        "Precinct":"33",
        "Votes":"399"
    },
    {
        "Party":"REP",
        "Precinct":"34",
        "Votes":"1975"
    },
    {
        "Party":"DEM",
        "Precinct":"34",
        "Votes":"1492"
    },
    {
        "Party":"REP",
        "Precinct":"35",
        "Votes":"818"
    },
    {
        "Party":"DEM",
        "Precinct":"35",
        "Votes":"493"
    },
    {
        "Party":"REP",
        "Precinct":"36",
        "Votes":"897"
    },
    {
        "Party":"DEM",
        "Precinct":"36",
        "Votes":"486"
    },
    {
        "Party":"REP",
        "Precinct":"37",
        "Votes":"966"
    },
    {
        "Party":"DEM",
        "Precinct":"37",
        "Votes":"386"
    },
    {
        "Party":"REP",
        "Precinct":"38",
        "Votes":"1509"
    },
    {
        "Party":"DEM",
        "Precinct":"38",
        "Votes":"892"
    },
    {
        "Party":"REP",
        "Precinct":"39",
        "Votes":"917"
    },
    {
        "Party":"DEM",
        "Precinct":"39",
        "Votes":"592"
    },
    {
        "Party":"REP",
        "Precinct":"40",
        "Votes":"2240"
    },
    {
        "Party":"DEM",
        "Precinct":"40",
        "Votes":"1570"
    },
    {
        "Party":"REP",
        "Precinct":"42",
        "Votes":"1470"
    },
    {
        "Party":"DEM",
        "Precinct":"42",
        "Votes":"688"
    },
    {
        "Party":"REP",
        "Precinct":"44",
        "Votes":"2723"
    },
    {
        "Party":"DEM",
        "Precinct":"44",
        "Votes":"1690"
    },
    {
        "Party":"REP",
        "Precinct":"46",
        "Votes":"1002"
    },
    {
        "Party":"DEM",
        "Precinct":"46",
        "Votes":"516"
    },
    {
        "Party":"REP",
        "Precinct":"47",
        "Votes":"1611"
    },
    {
        "Party":"DEM",
        "Precinct":"47",
        "Votes":"872"
    },
    {
        "Party":"REP",
        "Precinct":"48",
        "Votes":"1623"
    },
    {
        "Party":"DEM",
        "Precinct":"48",
        "Votes":"1047"
    },
    {
        "Party":"REP",
        "Precinct":"53",
        "Votes":"527"
    },
    {
        "Party":"DEM",
        "Precinct":"53",
        "Votes":"208"
    },
    {
        "Party":"REP",
        "Precinct":"54",
        "Votes":"1005"
    },
    {
        "Party":"DEM",
        "Precinct":"54",
        "Votes":"589"
    }
];

module.exports=votes;